"""Runtime support for Airflow DAGs and Python jobs generated by ds2af (DataStage to Airflow).

Modules:
    dsfunc    DataStage transformer / BASIC functions (Trim, Field, Iconv, StringToDate, ...)
    dsio      sequential files, data sets, hashed files and database access
    job       JobContext: parameters, #Param# substitution, macros, row counts, job status
    sequence  job-sequence support: activity execution, dsjob, trigger evaluation
"""

__version__ = "0.1.0"
