"""DataStage transformer and BASIC functions for code generated by ds2af.

Conventions, following DataStage:

* ``None`` is SQL NULL. Functions return None when an argument is None, except the
  null-handling functions (``is_null``, ``null_to_value``, ...).
* ``basic_*`` helpers implement DataStage BASIC (server jobs and job sequences): values are
  typeless, and numeric strings take part in arithmetic and comparisons as numbers.
* A row that cannot be processed raises ``RowError``; generated transformers send the row to
  their reject link, or drop it with a warning, as the parallel engine does.
"""

from __future__ import annotations

import datetime as _dt
import math as _math
import os as _os
import random as _random
import re as _re
from decimal import Decimal, InvalidOperation

FM = chr(254)
VM = chr(253)
SM = chr(252)
TM = chr(251)

# BASIC stores dates as days since 31 December 1967.
BASIC_EPOCH = _dt.date(1967, 12, 31)
# Two-digit years below this value belong to the 2000s (DataStage CenturyBreakYear).
CENTURY_BREAK = 30


class RowError(Exception):
    """The current row cannot be processed; the transformer rejects it."""


class NotTranslated(Exception):
    """Raised by placeholders the migrator emitted for code it could not translate."""


class DSJS:
    RUNNING = 0
    RUNOK = 1
    RUNWARN = 2
    RUNFAILED = 3
    QUEUED = 4
    VALOK = 11
    VALWARN = 12
    VALFAILED = 13
    RESET = 21
    CRASHED = 96
    STOPPED = 97
    NOTRUNNABLE = 98
    NOTRUNNING = 99


class DSJ:
    RUNNORMAL = 1
    RUNRESET = 2
    RUNVALIDATE = 3
    JOBSTATUS = 1
    JOBNAME = 2
    JOBCONTROLLER = 3
    JOBSTARTTIMESTAMP = 4
    JOBWAVENO = 5
    PARAMLIST = 6
    STAGELIST = 7
    USERSTATUS = 8
    JOBCONTROL = 9
    JOBPID = 10
    JOBLASTTIMESTAMP = 11
    JOBINVOCATIONS = 12
    JOBINTERIMSTATUS = 13
    JOBINVOCATIONID = 14
    ERRNONE = 1
    ERRWARN = 2
    ERRFATAL = 3


# --------------------------------------------------------------------------- placeholders

def untranslated(text):
    raise NotTranslated("DataStage expression was not translated: %s" % text)


def unresolved(name):
    raise NotTranslated("DataStage name could not be resolved: %s" % name)


def unsupported(name, *args):
    raise NotTranslated("DataStage function %s() has no Python implementation" % name)


# --------------------------------------------------------------------------- nulls and conversions

def _is_null(value):
    if value is None:
        return True
    if isinstance(value, float) and value != value:
        return True
    return type(value).__name__ in ("NAType", "NaTType")


def _any_null(*values):
    for value in values:
        if _is_null(value):
            return True
    return False


_NUMBER = _re.compile(r"^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$")


def _parse_number(text):
    """int for integral text, Decimal for other numbers, None when the text is not a number."""
    t = text.strip()
    if not t or not _NUMBER.match(t):
        return None
    if "." in t or "e" in t or "E" in t:
        try:
            return Decimal(t)
        except InvalidOperation:
            return None
    return int(t)


def _is_number(value):
    return isinstance(value, (int, float, Decimal)) and not isinstance(value, bool)


def _float_str(value):
    if value != value or value in (float("inf"), float("-inf")):
        return str(value)
    if value == int(value) and abs(value) < 1e15:
        return str(int(value))
    return repr(value)


def _decimal_str(value):
    text = format(value, "f")
    return "0" if text in ("-0", "") else text


def to_str(value):
    """The string DataStage produces when a value is used as a string."""
    if _is_null(value):
        return None
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, Decimal):
        return _decimal_str(value)
    if isinstance(value, float):
        return _float_str(value)
    if isinstance(value, _dt.datetime):
        text = value.strftime("%Y-%m-%d %H:%M:%S")
        return text + (".%06d" % value.microsecond if value.microsecond else "")
    if isinstance(value, _dt.date):
        return value.strftime("%Y-%m-%d")
    if isinstance(value, _dt.time):
        text = value.strftime("%H:%M:%S")
        return text + (".%06d" % value.microsecond if value.microsecond else "")
    if isinstance(value, bytes):
        return value.decode("latin-1")
    return str(value)


def to_number(value):
    """Numeric value with parallel-engine semantics; non-numeric strings reject the row."""
    if _is_null(value):
        return None
    if isinstance(value, bool):
        return int(value)
    if _is_number(value):
        return value
    if isinstance(value, str):
        number = _parse_number(value)
        if number is None:
            raise RowError("non-numeric value %r where a number is required" % (value,))
        return number
    raise RowError("value %r is not numeric" % (value,))


def basic_number(value):
    """Numeric value with BASIC semantics: empty and non-numeric strings count as 0."""
    if _is_null(value):
        return None
    if isinstance(value, bool):
        return int(value)
    if _is_number(value):
        return value
    number = _parse_number(to_str(value))
    return 0 if number is None else number


def _pair(a, b):
    if isinstance(a, float) and isinstance(b, Decimal):
        return a, float(b)
    if isinstance(a, Decimal) and isinstance(b, float):
        return float(a), b
    return a, b


def truth(value):
    """DataStage truthiness: null, 0, "0" and "" are false."""
    if _is_null(value):
        return False
    if isinstance(value, bool):
        return value
    if _is_number(value):
        return value != 0
    if isinstance(value, str):
        number = _parse_number(value)
        if number is not None:
            return number != 0
        return value != ""
    return True


def flag(value):
    """A boolean stored in a column: 1 or 0 (None stays None)."""
    if _is_null(value):
        return None
    return 1 if truth(value) else 0


# --------------------------------------------------------------------------- operators

def concat(*values):
    for value in values:
        if _is_null(value):
            return None
    return "".join(to_str(v) for v in values)


def neg(value):
    if _is_null(value):
        return None
    return -to_number(value)


def add(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(to_number(a), to_number(b))
    return a + b


def sub(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(to_number(a), to_number(b))
    return a - b


def mul(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(to_number(a), to_number(b))
    return a * b


def divide(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(to_number(a), to_number(b))
    if b == 0:
        raise RowError("division by zero")
    if isinstance(a, int) and isinstance(b, int):
        return a / b
    return a / b


def pwr(a, b):
    if _any_null(a, b):
        return None
    return float(to_number(a)) ** float(to_number(b))


def basic_add(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(basic_number(a), basic_number(b))
    return a + b


def basic_sub(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(basic_number(a), basic_number(b))
    return a - b


def basic_mul(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(basic_number(a), basic_number(b))
    return a * b


def basic_divide(a, b):
    if _any_null(a, b):
        return None
    a, b = _pair(basic_number(a), basic_number(b))
    if b == 0:
        raise RowError("division by zero")
    if isinstance(a, int) and isinstance(b, int):
        quotient = Decimal(a) / Decimal(b)
        return int(quotient) if quotient == int(quotient) else quotient
    return a / b


def basic_pwr(a, b):
    if _any_null(a, b):
        return None
    result = float(basic_number(a)) ** float(basic_number(b))
    return int(result) if result == int(result) and abs(result) < 1e15 else result


def _typed_pair(a, b):
    if isinstance(a, str) and _is_number(b):
        a = to_number(a)
    elif isinstance(b, str) and _is_number(a):
        b = to_number(b)
    elif isinstance(a, _dt.datetime) and not isinstance(b, _dt.datetime) and isinstance(b, _dt.date):
        b = _dt.datetime.combine(b, _dt.time())
    elif isinstance(b, _dt.datetime) and not isinstance(a, _dt.datetime) and isinstance(a, _dt.date):
        a = _dt.datetime.combine(a, _dt.time())
    elif isinstance(a, (_dt.date, _dt.time)) and isinstance(b, str):
        b = _parse_like(a, b)
    elif isinstance(b, (_dt.date, _dt.time)) and isinstance(a, str):
        a = _parse_like(b, a)
    return _pair(a, b)


def _parse_like(sample, text):
    if isinstance(sample, _dt.datetime):
        return string_to_timestamp(text)
    if isinstance(sample, _dt.date):
        return string_to_date(text)
    return string_to_time(text)


def eq(a, b):
    if _any_null(a, b):
        return None
    a, b = _typed_pair(a, b)
    return a == b


def ne(a, b):
    if _any_null(a, b):
        return None
    a, b = _typed_pair(a, b)
    return a != b


def lt(a, b):
    if _any_null(a, b):
        return None
    a, b = _typed_pair(a, b)
    return a < b


def gt(a, b):
    if _any_null(a, b):
        return None
    a, b = _typed_pair(a, b)
    return a > b


def le(a, b):
    if _any_null(a, b):
        return None
    a, b = _typed_pair(a, b)
    return a <= b


def ge(a, b):
    if _any_null(a, b):
        return None
    a, b = _typed_pair(a, b)
    return a >= b


def _basic_pair(a, b):
    """BASIC compares numerically when both sides are numbers or numeric strings, else as strings."""
    na = a if _is_number(a) else (_parse_number(a) if isinstance(a, str) else None)
    nb = b if _is_number(b) else (_parse_number(b) if isinstance(b, str) else None)
    if na is not None and nb is not None:
        return _pair(na, nb)
    return to_str(a), to_str(b)


def basic_eq(a, b):
    if _any_null(a, b):
        return None
    a, b = _basic_pair(a, b)
    return a == b


def basic_ne(a, b):
    if _any_null(a, b):
        return None
    a, b = _basic_pair(a, b)
    return a != b


def basic_lt(a, b):
    if _any_null(a, b):
        return None
    a, b = _basic_pair(a, b)
    return a < b


def basic_gt(a, b):
    if _any_null(a, b):
        return None
    a, b = _basic_pair(a, b)
    return a > b


def basic_le(a, b):
    if _any_null(a, b):
        return None
    a, b = _basic_pair(a, b)
    return a <= b


def basic_ge(a, b):
    if _any_null(a, b):
        return None
    a, b = _basic_pair(a, b)
    return a >= b


def _pattern_to_regex(pattern):
    parts = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c in "'\"\\":
            end = pattern.find(c, i + 1)
            if end < 0:
                end = len(pattern)
            parts.append(_re.escape(pattern[i + 1:end]))
            i = end + 1
            continue
        m = _re.match(r"(\d+)([NAX])", pattern[i:], _re.IGNORECASE)
        if m:
            count = int(m.group(1))
            cls = {"N": r"\d", "A": "[A-Za-z]", "X": "."}[m.group(2).upper()]
            parts.append(cls + ("*" if count == 0 else "{%d}" % count))
            i += len(m.group(0))
            continue
        parts.append(_re.escape(c))
        i += 1
    return "".join(parts)


def matches(value, pattern):
    """BASIC MATCHES: 3N = three digits, 0A = any letters, 2X = two characters, 'lit' = literal.
    Alternatives are separated by value marks."""
    if _any_null(value, pattern):
        return None
    text = to_str(value)
    for alternative in to_str(pattern).split(VM):
        if _re.fullmatch(_pattern_to_regex(alternative), text, _re.DOTALL):
            return True
    return False


# --------------------------------------------------------------------------- strings

def substr(value, start, length):
    """value[start, length] with 1-based start; start below 1 counts as 1."""
    if _any_null(value, start, length):
        return None
    text = to_str(value)
    s = max(int(basic_number(start)), 1)
    n = int(basic_number(length))
    if n <= 0:
        return ""
    return text[s - 1:s - 1 + n]


def substr_right(value, length):
    """value[length]: the trailing length characters."""
    if _any_null(value, length):
        return None
    text = to_str(value)
    n = int(basic_number(length))
    if n <= 0:
        return ""
    return text[-n:]


def field(value, delimiter, occurrence, count=1):
    """Field(string, delimiter, occurrence [, count]): 1-based delimited field(s)."""
    if _any_null(value, delimiter, occurrence, count):
        return None
    text = to_str(value)
    delim = to_str(delimiter)
    occ = max(int(basic_number(occurrence)), 1)
    n = max(int(basic_number(count)), 1)
    if delim == "":
        return text if occ == 1 else ""
    fields = text.split(delim)
    if occ > len(fields):
        return ""
    return delim.join(fields[occ - 1:occ - 1 + n])


_WS = " \t"


def _trim_chars(text, chars, option):
    option = (option or "R").upper()[:1]
    if option == "A":
        return "".join(c for c in text if c not in chars)
    if option in ("L", "F"):
        return text.lstrip(chars)
    if option in ("T", "E"):
        return text.rstrip(chars)
    if option == "B":
        return text.strip(chars)
    # R and D: leading, trailing and redundant (runs inside reduced to one character)
    stripped = text.strip(chars)
    out = []
    previous_was_trim = False
    for c in stripped:
        if c in chars:
            if not previous_was_trim:
                out.append(c)
            previous_was_trim = True
        else:
            out.append(c)
            previous_was_trim = False
    return "".join(out)


def trim(value, strip_char=None, option=None):
    """Trim(string [, char [, option]]). Default: remove leading/trailing spaces and tabs and
    reduce internal runs to one. Options: A all, B both ends, L/F leading, T/E trailing, R/D redundant."""
    if _is_null(value):
        return None
    text = to_str(value)
    chars = _WS if strip_char is None or to_str(strip_char) == "" else to_str(strip_char)[:1]
    if strip_char is None and option is None:
        return _trim_chars(text, chars, "R").replace("\t", " ") if "\t" in text else _trim_chars(text, chars, "R")
    return _trim_chars(text, chars, None if option is None else to_str(option))


def trim_f(value):
    if _is_null(value):
        return None
    return to_str(value).lstrip(_WS)


def trim_b(value):
    if _is_null(value):
        return None
    return to_str(value).rstrip(_WS)


def trim_leading_trailing(value):
    if _is_null(value):
        return None
    return to_str(value).strip(_WS)


def len_(value):
    if _is_null(value):
        return None
    return len(to_str(value))


def left(value, length):
    if _any_null(value, length):
        return None
    n = int(basic_number(length))
    return to_str(value)[:n] if n > 0 else ""


def right(value, length):
    if _any_null(value, length):
        return None
    n = int(basic_number(length))
    return to_str(value)[-n:] if n > 0 else ""


def upcase(value):
    return None if _is_null(value) else to_str(value).upper()


def downcase(value):
    return None if _is_null(value) else to_str(value).lower()


def index(value, substring, occurrence):
    """1-based position of the occurrence-th substring; 0 when absent."""
    if _any_null(value, substring, occurrence):
        return None
    text = to_str(value)
    sub = to_str(substring)
    occ = int(basic_number(occurrence))
    if occ < 1:
        return 0
    if sub == "":
        return 1 if occ == 1 else 0
    position = -1
    for _ in range(occ):
        position = text.find(sub, position + 1)
        if position < 0:
            return 0
    return position + 1


def count(value, substring):
    """Occurrences of substring, overlapping ones included (BASIC COUNT)."""
    if _any_null(value, substring):
        return None
    text = to_str(value)
    sub = to_str(substring)
    if sub == "":
        return 0
    total = 0
    position = text.find(sub)
    while position >= 0:
        total += 1
        position = text.find(sub, position + 1)
    return total


def dcount(value, delimiter):
    """Number of delimited fields; 0 for an empty string."""
    if _any_null(value, delimiter):
        return None
    text = to_str(value)
    if text == "":
        return 0
    delim = to_str(delimiter)
    return 1 if delim == "" else text.count(delim) + 1


def str_repeat(value, times):
    if _any_null(value, times):
        return None
    n = int(basic_number(times))
    return to_str(value) * n if n > 0 else ""


def space(length):
    if _is_null(length):
        return None
    n = int(basic_number(length))
    return " " * n if n > 0 else ""


def char(code):
    if _is_null(code):
        return None
    return chr(int(basic_number(code)))


def seq(value):
    if _is_null(value):
        return None
    text = to_str(value)
    return ord(text[0]) if text else 0


def convert(from_chars, to_chars, value):
    """Convert(from, to, string): replace each character of from with the matching one of to;
    characters of from without a counterpart are removed."""
    if _any_null(from_chars, to_chars, value):
        return None
    source = to_str(from_chars)
    target = to_str(to_chars)
    table = {}
    for i, c in enumerate(source):
        if c not in table:
            table[c] = target[i] if i < len(target) else ""
    return "".join(table.get(c, c) for c in to_str(value))


def ereplace(value, old, new, occurrences=0, begin=1):
    """Ereplace/Change: replace occurrences (0 = all) of old, starting with the begin-th."""
    if _any_null(value, old, new):
        return None
    text = to_str(value)
    old_text = to_str(old)
    new_text = to_str(new)
    if old_text == "":
        return new_text + text
    occ = int(basic_number(occurrences)) if occurrences is not None else 0
    first = max(int(basic_number(begin)) if begin is not None else 1, 1)
    out = []
    position = 0
    seen = 0
    replaced = 0
    while True:
        found = text.find(old_text, position)
        if found < 0:
            break
        seen += 1
        if seen >= first and (occ <= 0 or replaced < occ):
            out.append(text[position:found])
            out.append(new_text)
            replaced += 1
        else:
            out.append(text[position:found + len(old_text)])
        position = found + len(old_text)
    out.append(text[position:])
    return "".join(out)


def compare(a, b, justification="L"):
    """-1, 0 or 1. 'R' justification compares numbers numerically and right-aligns strings."""
    if _any_null(a, b):
        return None
    x, y = to_str(a), to_str(b)
    if to_str(justification or "L").upper().startswith("R"):
        nx, ny = _parse_number(x), _parse_number(y)
        if nx is not None and ny is not None:
            nx, ny = _pair(nx, ny)
            return (nx > ny) - (nx < ny)
        width = max(len(x), len(y))
        x, y = x.rjust(width), y.rjust(width)
    return (x > y) - (x < y)


def alpha(value):
    if _is_null(value):
        return None
    text = to_str(value)
    return text != "" and text.isalpha()


def num(value):
    """BASIC NUM: true for numeric strings, and for the empty string."""
    if _is_null(value):
        return None
    if _is_number(value):
        return True
    text = to_str(value)
    return text == "" or _parse_number(text) is not None


def alnum(value):
    if _is_null(value):
        return None
    text = to_str(value)
    return text != "" and text.isalnum()


def dquote(value):
    return None if _is_null(value) else '"' + to_str(value) + '"'


def squote(value):
    return None if _is_null(value) else "'" + to_str(value) + "'"


def strip_white_space(value):
    if _is_null(value):
        return None
    return "".join(to_str(value).split())


def compact_white_space(value):
    if _is_null(value):
        return None
    return _re.sub(r"\s+", " ", to_str(value))


def pad_string(value, pad, length):
    """PadString(string, padstring, n): appends n copies of the first character of padstring."""
    if _any_null(value, pad, length):
        return None
    pad_text = to_str(pad)
    n = int(basic_number(length))
    return to_str(value) + (pad_text[:1] * n if n > 0 and pad_text else "")


def soundex(value):
    if _is_null(value):
        return None
    text = "".join(c for c in to_str(value).upper() if c.isalpha())
    if not text:
        return ""
    codes = {}
    for letters, digit in (("BFPV", "1"), ("CGJKQSXZ", "2"), ("DT", "3"), ("L", "4"), ("MN", "5"), ("R", "6")):
        for letter in letters:
            codes[letter] = digit
    result = text[0]
    previous = codes.get(text[0], "")
    for c in text[1:]:
        digit = codes.get(c, "")
        if digit and digit != previous:
            result += digit
        if c not in "HW":
            previous = digit
    return (result + "000")[:4]


def dtx(value, width=0):
    if _is_null(value):
        return None
    text = "%X" % int(basic_number(value))
    return text.rjust(int(basic_number(width or 0)), "0")


def xtd(value):
    if _is_null(value):
        return None
    try:
        return int(to_str(value).strip(), 16)
    except ValueError:
        raise RowError("not a hexadecimal number: %r" % (value,))


def ustring(value, *_):
    return None if _is_null(value) else to_str(value)


def like(value, pattern):
    """SQL LIKE with % and _ wildcards (Filter stage where clauses)."""
    if _any_null(value, pattern):
        return None
    regex = "".join(".*" if c == "%" else "." if c == "_" else _re.escape(c) for c in to_str(pattern))
    return _re.fullmatch(regex, to_str(value), _re.DOTALL) is not None


# --------------------------------------------------------------------------- null handling functions

def is_null(value):
    return _is_null(value)


def is_not_null(value):
    return not _is_null(value)


def null_to_value(value, replacement):
    return replacement if _is_null(value) else value


def null_to_zero(value):
    return 0 if _is_null(value) else value


def null_to_empty(value):
    return "" if _is_null(value) else value


def set_null():
    return None


# --------------------------------------------------------------------------- DataStage date/time formats

_MONTH_ABBR = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
_MONTH_NAME = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST",
               "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"]
_DAY_ABBR = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
_DAY_NAME = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]

_TOKEN = _re.compile(
    r"%(?P<cutoff>\d{4})?(?P<tok>yyyy|yy|mmmm|mmm|mm|m|ddd|dd|d|hh|h|nn|n|ss\.\d+|ss|s|aa|eeee|eee|%)",
    _re.IGNORECASE)

DEFAULT_DATE_FORMAT = "%yyyy-%mm-%dd"
DEFAULT_TIME_FORMAT = "%hh:%nn:%ss"
DEFAULT_TIMESTAMP_FORMAT = "%yyyy-%mm-%dd %hh:%nn:%ss"

_format_cache = {}


def _compile_format(fmt):
    cached = _format_cache.get(fmt)
    if cached is not None:
        return cached
    pattern = []
    fields = []
    pos = 0
    for m in _TOKEN.finditer(fmt):
        pattern.append(_re.escape(fmt[pos:m.start()]))
        tok = m.group("tok").lower()
        cutoff = int(m.group("cutoff")) if m.group("cutoff") else None
        pos = m.end()
        if tok == "%":
            pattern.append("%")
            continue
        name = "f%d" % len(fields)
        fields.append((name, tok, cutoff))
        if tok == "yyyy":
            regex = r"\d{4}"
        elif tok in ("yy", "mm", "dd", "hh", "nn", "ss"):
            regex = r"\d{2}"
        elif tok in ("m", "d", "h", "n", "s"):
            regex = r"\d{1,2}"
        elif tok == "ddd":
            regex = r"\d{3}"
        elif tok == "mmm":
            regex = "[A-Za-z]{3}"
        elif tok in ("mmmm", "eeee"):
            regex = "[A-Za-z]+"
        elif tok == "eee":
            regex = "[A-Za-z]{3}"
        elif tok == "aa":
            regex = "[AaPp][Mm]"
        else:  # ss.N
            regex = r"\d{2}(?:\.\d{1,%d})?" % int(tok.split(".")[1])
        pattern.append("(?P<%s>%s)" % (name, regex))
    pattern.append(_re.escape(fmt[pos:]))
    compiled = (_re.compile("^" + "".join(pattern) + "$", _re.IGNORECASE), fields)
    _format_cache[fmt] = compiled
    return compiled


def _parse_components(text, fmt):
    regex, fields = _compile_format(fmt)
    m = regex.match(text)
    if not m:
        raise RowError("value %r does not match format %r" % (text, fmt))
    c = {"year": 1, "month": 1, "day": 1, "hour": 0, "minute": 0, "second": 0, "micro": 0, "yday": None, "pm": None}
    for name, tok, cutoff in fields:
        value = m.group(name)
        if tok == "yyyy":
            c["year"] = int(value)
        elif tok == "yy":
            base = cutoff if cutoff is not None else 1900
            year = (base // 100) * 100 + int(value)
            if year < base:
                year += 100
            c["year"] = year
        elif tok in ("mm", "m"):
            c["month"] = int(value)
        elif tok == "mmm":
            c["month"] = _MONTH_ABBR.index(value.upper()) + 1 if value.upper() in _MONTH_ABBR else 0
        elif tok == "mmmm":
            c["month"] = _MONTH_NAME.index(value.upper()) + 1 if value.upper() in _MONTH_NAME else 0
        elif tok in ("dd", "d"):
            c["day"] = int(value)
        elif tok == "ddd":
            c["yday"] = int(value)
        elif tok in ("hh", "h"):
            c["hour"] = int(value)
        elif tok in ("nn", "n"):
            c["minute"] = int(value)
        elif tok in ("ss", "s") or tok.startswith("ss."):
            whole, _, fraction = value.partition(".")
            c["second"] = int(whole)
            if fraction:
                c["micro"] = int((fraction + "000000")[:6])
        elif tok == "aa":
            c["pm"] = value.upper() == "PM"
    if c["pm"] is not None:
        c["hour"] = c["hour"] % 12 + (12 if c["pm"] else 0)
    if c["month"] == 0:
        raise RowError("value %r has an unknown month name" % (text,))
    return c


def _format_value(value, fmt):
    regex, fields = _compile_format(fmt)
    out = []
    pos = 0
    for m in _TOKEN.finditer(fmt):
        out.append(fmt[pos:m.start()])
        pos = m.end()
        tok = m.group("tok").lower()
        if tok == "%":
            out.append("%")
        elif tok == "yyyy":
            out.append("%04d" % value.year)
        elif tok == "yy":
            out.append("%02d" % (value.year % 100))
        elif tok == "mm":
            out.append("%02d" % value.month)
        elif tok == "m":
            out.append("%d" % value.month)
        elif tok == "mmm":
            out.append(_MONTH_ABBR[value.month - 1].capitalize())
        elif tok == "mmmm":
            out.append(_MONTH_NAME[value.month - 1].capitalize())
        elif tok == "dd":
            out.append("%02d" % value.day)
        elif tok == "d":
            out.append("%d" % value.day)
        elif tok == "ddd":
            out.append("%03d" % value.timetuple().tm_yday)
        elif tok == "eee":
            out.append(_DAY_ABBR[value.weekday()].capitalize())
        elif tok == "eeee":
            out.append(_DAY_NAME[value.weekday()].capitalize())
        elif tok in ("hh", "h"):
            hour = value.hour
            if "%aa" in fmt.lower():
                hour = hour % 12 or 12
            out.append("%02d" % hour if tok == "hh" else "%d" % hour)
        elif tok == "nn":
            out.append("%02d" % value.minute)
        elif tok == "n":
            out.append("%d" % value.minute)
        elif tok == "ss":
            out.append("%02d" % value.second)
        elif tok == "s":
            out.append("%d" % value.second)
        elif tok.startswith("ss."):
            digits = int(tok.split(".")[1])
            out.append("%02d" % value.second)
            if digits > 0:
                out.append("." + ("%06d" % value.microsecond)[:digits].ljust(digits, "0"))
        elif tok == "aa":
            out.append("PM" if value.hour >= 12 else "AM")
    out.append(fmt[pos:])
    return "".join(out)


def string_to_date(value, fmt=None):
    if _is_null(value):
        return None
    if isinstance(value, _dt.datetime):
        return value.date()
    if isinstance(value, _dt.date):
        return value
    c = _parse_components(to_str(value).strip(), to_str(fmt) if fmt else DEFAULT_DATE_FORMAT)
    try:
        if c["yday"] is not None:
            return _dt.date(c["year"], 1, 1) + _dt.timedelta(days=c["yday"] - 1)
        return _dt.date(c["year"], c["month"], c["day"])
    except ValueError as exc:
        raise RowError("invalid date %r: %s" % (value, exc))


def date_to_string(value, fmt=None):
    if _is_null(value):
        return None
    return _format_value(string_to_date(value), to_str(fmt) if fmt else DEFAULT_DATE_FORMAT)


def string_to_time(value, fmt=None):
    if _is_null(value):
        return None
    if isinstance(value, _dt.datetime):
        return value.time()
    if isinstance(value, _dt.time):
        return value
    c = _parse_components(to_str(value).strip(), to_str(fmt) if fmt else DEFAULT_TIME_FORMAT)
    try:
        return _dt.time(c["hour"], c["minute"], c["second"], c["micro"])
    except ValueError as exc:
        raise RowError("invalid time %r: %s" % (value, exc))


def time_to_string(value, fmt=None):
    if _is_null(value):
        return None
    t = string_to_time(value)
    return _format_value(_dt.datetime.combine(_dt.date(2000, 1, 1), t), to_str(fmt) if fmt else DEFAULT_TIME_FORMAT)


def string_to_timestamp(value, fmt=None):
    if _is_null(value):
        return None
    if isinstance(value, _dt.datetime):
        return value
    if isinstance(value, _dt.date):
        return _dt.datetime.combine(value, _dt.time())
    c = _parse_components(to_str(value).strip(), to_str(fmt) if fmt else DEFAULT_TIMESTAMP_FORMAT)
    try:
        return _dt.datetime(c["year"], c["month"], c["day"], c["hour"], c["minute"], c["second"], c["micro"])
    except ValueError as exc:
        raise RowError("invalid timestamp %r: %s" % (value, exc))


def timestamp_to_string(value, fmt=None):
    if _is_null(value):
        return None
    return _format_value(string_to_timestamp(value), to_str(fmt) if fmt else DEFAULT_TIMESTAMP_FORMAT)


def timestamp_to_date(value):
    return None if _is_null(value) else string_to_timestamp(value).date()


def timestamp_to_time(value):
    return None if _is_null(value) else string_to_timestamp(value).time()


def date_to_timestamp(value):
    return None if _is_null(value) else _dt.datetime.combine(string_to_date(value), _dt.time())


def _valid(func, value, *args):
    try:
        func(value, *args)
        return True
    except (RowError, ValueError, TypeError, InvalidOperation):
        return False


def is_valid_date(value):
    return not _is_null(value) and _valid(string_to_date, value)


def is_valid_time(value):
    return not _is_null(value) and _valid(string_to_time, value)


def is_valid_timestamp(value):
    return not _is_null(value) and _valid(string_to_timestamp, value)


def is_valid_decimal(value, *_):
    return not _is_null(value) and _valid(string_to_decimal, value)


def is_valid(type_name, value):
    """IsValid("int32", "123"): whether the value converts to the named parallel type."""
    if _is_null(value):
        return False
    t = to_str(type_name).lower()
    text = to_str(value).strip()
    if t.startswith(("int", "uint")):
        n = _parse_number(text)
        if not isinstance(n, int):
            return False
        bits = int(_re.sub(r"\D", "", t) or 32)
        if t.startswith("u"):
            return 0 <= n < 2 ** bits
        return -(2 ** (bits - 1)) <= n < 2 ** (bits - 1)
    if t in ("sfloat", "dfloat", "float", "double"):
        return _parse_number(text) is not None
    if t.startswith("decimal"):
        return _parse_number(text) is not None
    if t == "date":
        return _valid(string_to_date, text)
    if t == "time":
        return _valid(string_to_time, text)
    if t == "timestamp":
        return _valid(string_to_timestamp, text)
    return True


# --------------------------------------------------------------------------- numeric conversions

def string_to_decimal(value, rounding=None):
    if _is_null(value):
        return None
    if isinstance(value, Decimal):
        return value
    if _is_number(value):
        return Decimal(str(value))
    text = to_str(value).strip()
    try:
        return Decimal(text if text else "0")
    except InvalidOperation:
        raise RowError("invalid decimal %r" % (value,))


def decimal_to_string(value, option=None):
    if _is_null(value):
        return None
    number = string_to_decimal(value)
    text = _decimal_str(number)
    if option is not None and "suppress_zero" in to_str(option).lower() and "." in text:
        text = text.rstrip("0").rstrip(".")
    return text


def decimal_to_decimal(value, rounding=None):
    return None if _is_null(value) else string_to_decimal(value)


def decimal_to_dfloat(value, *_):
    return None if _is_null(value) else float(string_to_decimal(value))


def dfloat_to_decimal(value, *_):
    if _is_null(value):
        return None
    return Decimal(repr(float(value))) if not isinstance(value, Decimal) else value


def dfloat_to_string_no_exp(value, scale):
    if _any_null(value, scale):
        return None
    return format(float(value), ".%df" % int(scale))


def as_integer(value):
    if _is_null(value):
        return None
    return int(to_number(value))


def as_float(value):
    if _is_null(value):
        return None
    return float(to_number(value))


def as_decimal(value):
    return string_to_decimal(value)


# --------------------------------------------------------------------------- parallel date/time functions

def current_date():
    return _dt.date.today()


def current_time():
    return _dt.datetime.now().time().replace(microsecond=0)


def current_time_ms():
    return _dt.datetime.now().time()


def current_timestamp():
    return _dt.datetime.now().replace(microsecond=0)


def current_timestamp_ms():
    return _dt.datetime.now()


def _date(value):
    return string_to_date(value)


def _timestamp(value):
    return string_to_timestamp(value)


def date_from_days_since(days, base=None):
    if _is_null(days):
        return None
    origin = _date(base) if base is not None else _dt.date(1970, 1, 1)
    return origin + _dt.timedelta(days=int(to_number(days)))


def days_since_from_date(value, source):
    if _any_null(value, source):
        return None
    return (_date(value) - _date(source)).days


# Julian Day Number of 0001-01-01 (proleptic Gregorian) is 1721426, i.e. ordinal + 1721425.
_JULIAN_OFFSET = 1721425


def date_from_julian_day(day):
    if _is_null(day):
        return None
    return _dt.date.fromordinal(int(to_number(day)) - _JULIAN_OFFSET)


def julian_day_from_date(value):
    if _is_null(value):
        return None
    return _date(value).toordinal() + _JULIAN_OFFSET


def date_from_components(year, month, day):
    if _any_null(year, month, day):
        return None
    try:
        return _dt.date(int(to_number(year)), int(to_number(month)), int(to_number(day)))
    except ValueError as exc:
        raise RowError("invalid date components: %s" % exc)


def date_offset_by_days(value, days):
    if _any_null(value, days):
        return None
    return _date(value) + _dt.timedelta(days=int(to_number(days)))


def _add_months(d, months):
    month_index = d.year * 12 + (d.month - 1) + months
    year, month = divmod(month_index, 12)
    month += 1
    last_day = [31, 29 if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0) else 28,
                31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1]
    return d.replace(year=year, month=month, day=min(d.day, last_day))


def date_offset_by_components(value, years, months, days):
    if _any_null(value, years, months, days):
        return None
    d = _add_months(_date(value), int(to_number(years)) * 12 + int(to_number(months)))
    return d + _dt.timedelta(days=int(to_number(days)))


def time_from_components(hours, minutes, seconds, microseconds=0):
    if _any_null(hours, minutes, seconds):
        return None
    return _dt.time(int(to_number(hours)), int(to_number(minutes)), int(to_number(seconds)), int(to_number(microseconds or 0)))


def time_from_midnight_seconds(seconds):
    if _is_null(seconds):
        return None
    total = Decimal(str(to_number(seconds)))
    whole = int(total)
    micro = int((total - whole) * 1000000)
    return _dt.time(whole // 3600 % 24, whole // 60 % 60, whole % 60, micro)


def midnight_seconds_from_time(value):
    if _is_null(value):
        return None
    t = string_to_time(value)
    seconds = t.hour * 3600 + t.minute * 60 + t.second
    return Decimal(seconds) + Decimal(t.microsecond) / Decimal(1000000) if t.microsecond else seconds


def timestamp_from_date_time(date_value, time_value):
    if _any_null(date_value, time_value):
        return None
    return _dt.datetime.combine(_date(date_value), string_to_time(time_value))


def timestamp_from_seconds_since(seconds, base=None):
    if _is_null(seconds):
        return None
    origin = _timestamp(base) if base is not None else _dt.datetime(1970, 1, 1)
    return origin + _dt.timedelta(seconds=float(to_number(seconds)))


def seconds_since_from_timestamp(value, base):
    if _any_null(value, base):
        return None
    delta = _timestamp(value) - _timestamp(base)
    seconds = delta.days * 86400 + delta.seconds
    return Decimal(seconds) + Decimal(delta.microseconds) / Decimal(1000000) if delta.microseconds else seconds


def timestamp_from_timet(value):
    if _is_null(value):
        return None
    return _dt.datetime(1970, 1, 1) + _dt.timedelta(seconds=int(to_number(value)))


def timet_from_timestamp(value):
    if _is_null(value):
        return None
    delta = _timestamp(value) - _dt.datetime(1970, 1, 1)
    return delta.days * 86400 + delta.seconds


def timestamp_offset_by_seconds(value, seconds):
    if _any_null(value, seconds):
        return None
    return _timestamp(value) + _dt.timedelta(seconds=float(to_number(seconds)))


def timestamp_offset_by_components(value, years, months, days, hours, minutes, seconds):
    if _any_null(value, years, months, days, hours, minutes, seconds):
        return None
    ts = _timestamp(value)
    shifted = _add_months(ts.date(), int(to_number(years)) * 12 + int(to_number(months)))
    ts = _dt.datetime.combine(shifted, ts.time())
    return ts + _dt.timedelta(days=int(to_number(days)), hours=int(to_number(hours)),
                              minutes=int(to_number(minutes)), seconds=float(to_number(seconds)))


def time_offset_by_seconds(value, seconds):
    if _any_null(value, seconds):
        return None
    base = _dt.datetime.combine(_dt.date(2000, 1, 1), string_to_time(value))
    return (base + _dt.timedelta(seconds=float(to_number(seconds)))).time()


def time_offset_by_components(value, hours, minutes, seconds):
    if _any_null(value, hours, minutes, seconds):
        return None
    base = _dt.datetime.combine(_dt.date(2000, 1, 1), string_to_time(value))
    return (base + _dt.timedelta(hours=int(to_number(hours)), minutes=int(to_number(minutes)),
                                 seconds=float(to_number(seconds)))).time()


def _time_part(value):
    if isinstance(value, _dt.datetime):
        return value.time()
    return string_to_time(value)


def hours_from_time(value):
    return None if _is_null(value) else _time_part(value).hour


def minutes_from_time(value):
    return None if _is_null(value) else _time_part(value).minute


def seconds_from_time(value):
    if _is_null(value):
        return None
    t = _time_part(value)
    return Decimal(t.second) + Decimal(t.microsecond) / Decimal(1000000) if t.microsecond else t.second


def microseconds_from_time(value):
    return None if _is_null(value) else _time_part(value).microsecond


def year_from_date(value):
    return None if _is_null(value) else _date(value).year


def month_from_date(value):
    return None if _is_null(value) else _date(value).month


def month_day_from_date(value):
    return None if _is_null(value) else _date(value).day


def _weekday_index(name):
    key = to_str(name).strip().upper()[:3]
    if key not in _DAY_ABBR:
        raise RowError("unknown weekday %r" % (name,))
    return _DAY_ABBR.index(key)


def weekday_from_date(value, origin="sunday"):
    """Day of the week, 0 for the origin day (Sunday by default)."""
    if _is_null(value):
        return None
    return (_date(value).weekday() - _weekday_index(origin or "sunday")) % 7


def yearday_from_date(value):
    return None if _is_null(value) else _date(value).timetuple().tm_yday


def yearweek_from_date(value):
    return None if _is_null(value) else _date(value).isocalendar()[1]


def next_weekday_from_date(value, weekday):
    if _any_null(value, weekday):
        return None
    d = _date(value)
    ahead = (_weekday_index(weekday) - d.weekday()) % 7 or 7
    return d + _dt.timedelta(days=ahead)


def previous_weekday_from_date(value, weekday):
    if _any_null(value, weekday):
        return None
    d = _date(value)
    back = (d.weekday() - _weekday_index(weekday)) % 7 or 7
    return d - _dt.timedelta(days=back)


def nth_weekday_from_date(value, weekday, n):
    if _any_null(value, weekday, n):
        return None
    count_ = int(to_number(n))
    if count_ >= 0:
        first = next_weekday_from_date(value, weekday)
        return first + _dt.timedelta(weeks=max(count_ - 1, 0))
    first = previous_weekday_from_date(value, weekday)
    return first - _dt.timedelta(weeks=-count_ - 1)


# --------------------------------------------------------------------------- BASIC dates and times

def basic_date():
    return (_dt.date.today() - BASIC_EPOCH).days


def basic_time():
    now = _dt.datetime.now()
    return now.hour * 3600 + now.minute * 60 + now.second


def basic_day():
    return _dt.date.today().day


def basic_month():
    return _dt.date.today().month


def basic_year():
    return _dt.date.today().year % 100


def basic_year4():
    return _dt.date.today().year


def time_date():
    now = _dt.datetime.now()
    return "%02d:%02d:%02d %02d %s %04d" % (now.hour, now.minute, now.second, now.day, _MONTH_ABBR[now.month - 1], now.year)


_D_CODE = _re.compile(r"^D(?P<digits>[0-4])?(?P<sep>[^A-Za-z0-9\[\]]?)(?P<order>[YMDE]{0,3})(?:\[(?P<widths>[^\]]*)\])?$",
                      _re.IGNORECASE)


def _date_code(code):
    m = _D_CODE.match(code.strip())
    if not m:
        raise NotTranslated("unsupported date conversion code %r" % code)
    digits = int(m.group("digits")) if m.group("digits") else 4
    sep = m.group("sep") or ""
    order = (m.group("order") or "").upper()
    if order == "E":
        order = "DMY"
    widths = [w.strip().upper() for w in (m.group("widths") or "").split(",")] if m.group("widths") else []
    alpha_default = sep == "" and not order
    if not order:
        order = "DMY" if alpha_default else "MDY"
    return digits, sep, order, widths, alpha_default


def _oconv_date(value, code):
    digits, sep, order, widths, alpha_default = _date_code(code)
    d = BASIC_EPOCH + _dt.timedelta(days=int(basic_number(value)))
    parts = []
    for i, part in enumerate(order):
        width = widths[i] if i < len(widths) else ""
        if part == "Y":
            size = int(width) if width.isdigit() else digits
            parts.append(("%04d" % d.year)[-size:] if size > 0 else "")
        elif part == "M":
            if width.startswith("A") or (alpha_default and not width):
                name = _MONTH_NAME[d.month - 1]
                size = int(width[1:]) if width[1:].isdigit() else (3 if alpha_default else len(name))
                parts.append(name[:size])
            else:
                parts.append("%02d" % d.month if not width or width == "2" else "%d" % d.month)
        else:
            parts.append("%02d" % d.day if not width or width == "2" else "%d" % d.day)
    return (sep or " ").join(p for p in parts if p != "")


def _iconv_date(text, code):
    digits, sep, order, widths, alpha_default = _date_code(code)
    tokens = [t for t in _re.split(r"[^A-Za-z0-9]+", text.strip()) if t]
    if len(tokens) == 1 and len(tokens[0]) in (6, 8) and tokens[0].isdigit():
        raw = tokens[0]
        sizes = {"Y": 4 if len(raw) == 8 else 2, "M": 2, "D": 2}
        tokens = []
        pos = 0
        for part in order:
            tokens.append(raw[pos:pos + sizes[part]])
            pos += sizes[part]
    if len(tokens) != len(order):
        raise RowError("value %r does not match date code %r" % (text, code))
    year = month = day = None
    for part, token in zip(order, tokens):
        if part == "Y":
            year = int(token)
            if len(token) <= 2:
                year += 2000 if year < CENTURY_BREAK else 1900
        elif part == "M":
            if token.isdigit():
                month = int(token)
            else:
                key = token.upper()[:3]
                if key not in _MONTH_ABBR:
                    raise RowError("unknown month %r" % token)
                month = _MONTH_ABBR.index(key) + 1
        else:
            day = int(token)
    try:
        return (_dt.date(year, month, day) - BASIC_EPOCH).days
    except (TypeError, ValueError) as exc:
        raise RowError("invalid date %r: %s" % (text, exc))


_MD_CODE = _re.compile(r"^M[DR](?P<scale>\d)?(?P<rest>.*)$", _re.IGNORECASE)


def _oconv_md(value, code):
    m = _MD_CODE.match(code.strip())
    scale = int(m.group("scale") or 0)
    rest = m.group("rest") or ""
    number = Decimal(str(basic_number(value))) / (Decimal(10) ** scale)
    text = format(number.quantize(Decimal(1).scaleb(-scale)) if scale else number.to_integral_value(), "f")
    negative = text.startswith("-")
    if negative:
        text = text[1:]
    if "," in rest:
        whole, _, fraction = text.partition(".")
        whole = "{:,}".format(int(whole))
        text = whole + ("." + fraction if fraction else "")
    if "$" in rest:
        text = "$" + text
    if negative:
        text = text + "-" if "-" in rest else "-" + text
    return text


def _iconv_md(text, code):
    m = _MD_CODE.match(code.strip())
    scale = int(m.group("scale") or 0)
    cleaned = text.replace(",", "").replace("$", "").strip()
    negative = cleaned.endswith("-")
    if negative:
        cleaned = "-" + cleaned[:-1]
    try:
        number = Decimal(cleaned) * (Decimal(10) ** scale)
    except InvalidOperation:
        raise RowError("value %r does not match code %r" % (text, code))
    return int(number.to_integral_value())


def _oconv_time(value, code):
    seconds = int(basic_number(value)) % 86400
    h, rem = divmod(seconds, 3600)
    mi, s = divmod(rem, 60)
    upper = code.upper()
    twelve = "H" in upper[2:]
    with_seconds = "S" in upper[2:]
    suffix = ""
    if twelve:
        suffix = "PM" if h >= 12 else "AM"
        h = h % 12 or 12
    text = "%02d:%02d" % (h, mi)
    if with_seconds:
        text += ":%02d" % s
    return text + suffix


def _iconv_time(text, code):
    m = _re.match(r"^\s*(\d{1,2})(?::(\d{1,2}))?(?::(\d{1,2}))?\s*([AaPp][Mm])?\s*$", text)
    if not m:
        raise RowError("value %r does not match time code %r" % (text, code))
    h = int(m.group(1))
    mi = int(m.group(2) or 0)
    s = int(m.group(3) or 0)
    if m.group(4):
        h = h % 12 + (12 if m.group(4).upper() == "PM" else 0)
    return h * 3600 + mi * 60 + s


def _mc(text, code):
    kind = code.upper()[2:]
    if kind == "U":
        return text.upper()
    if kind == "L":
        return text.lower()
    if kind == "T":
        return text.title()
    if kind == "N":
        return "".join(c for c in text if c.isdigit())
    if kind == "A":
        return "".join(c for c in text if c.isalpha())
    if kind == "/N":
        return "".join(c for c in text if not c.isdigit())
    if kind == "/A":
        return "".join(c for c in text if not c.isalpha())
    raise NotTranslated("unsupported conversion code %r" % code)


def _group(text, code):
    m = _re.match(r"^G(\d*)(.)(\d+)$", code)
    if not m:
        raise NotTranslated("unsupported conversion code %r" % code)
    skip = int(m.group(1) or 0)
    return field(text, m.group(2), skip + 1, int(m.group(3)))


def oconv(value, code):
    """Oconv(internal, code): D (dates), MT (times), MD/MR (scaled decimals), MC (case/class), G (groups)."""
    if _any_null(value, code):
        return None
    c = to_str(code).strip()
    upper = c.upper()
    if to_str(value) == "" and not upper.startswith("MC"):
        return ""
    if upper.startswith("D"):
        return _oconv_date(value, c)
    if upper.startswith("MT"):
        return _oconv_time(value, c)
    if upper.startswith("MD") or upper.startswith("MR"):
        return _oconv_md(value, c)
    if upper.startswith("MC"):
        return _mc(to_str(value), c)
    if upper.startswith("G"):
        return _group(to_str(value), c)
    raise NotTranslated("unsupported Oconv code %r" % c)


def iconv(value, code):
    """Iconv(external, code): the inverse of Oconv for D, MT and MD/MR codes."""
    if _any_null(value, code):
        return None
    c = to_str(code).strip()
    upper = c.upper()
    text = to_str(value)
    if text.strip() == "" and not upper.startswith("MC"):
        return ""
    if upper.startswith("D"):
        return _iconv_date(text, c)
    if upper.startswith("MT"):
        return _iconv_time(text, c)
    if upper.startswith("MD") or upper.startswith("MR"):
        return _iconv_md(text, c)
    if upper.startswith("MC"):
        return _mc(text, c)
    if upper.startswith("G"):
        return _group(text, c)
    raise NotTranslated("unsupported Iconv code %r" % c)


_FMT_CODE = _re.compile(r"^(?P<width>\d*)(?:'(?P<fill>.)')?(?P<just>[LRCT])(?P<scale>\d*)(?P<comma>,?)(?P<mask>.*)$", _re.IGNORECASE)


def fmt(value, code):
    """BASIC FMT: width, optional 'fill', justification L/R/C/T, decimals, thousands comma, # masks."""
    if _any_null(value, code):
        return None
    c = to_str(code)
    m = _FMT_CODE.match(c)
    if not m:
        raise NotTranslated("unsupported FMT code %r" % c)
    text = to_str(value)
    if m.group("scale"):
        number = basic_number(value)
        scale = int(m.group("scale"))
        text = format(Decimal(str(number)).quantize(Decimal(1).scaleb(-scale)), "f")
        if m.group("comma"):
            whole, _, fraction = text.partition(".")
            negative = whole.startswith("-")
            whole = "{:,}".format(abs(int(whole)))
            text = ("-" if negative else "") + whole + ("." + fraction if fraction else "")
    mask = m.group("mask") or ""
    if mask.startswith("#") or "#" in mask:
        slots = mask.count("#")
        just = m.group("just").upper()
        chars = list(text[-slots:] if just == "R" else text[:slots])
        if just == "R":
            chars = [" "] * (slots - len(chars)) + chars
        else:
            chars = chars + [" "] * (slots - len(chars))
        out = []
        for ch in mask:
            out.append(chars.pop(0) if ch == "#" else ch)
        return "".join(out)
    width = int(m.group("width") or 0)
    fill = m.group("fill") or " "
    just = m.group("just").upper()
    if width <= 0:
        return text
    if just == "R":
        return text.rjust(width, fill)[-width:]
    if just == "C":
        return text.center(width, fill)[:width]
    return text.ljust(width, fill)[:width]


# --------------------------------------------------------------------------- numbers

def abs_(value):
    return None if _is_null(value) else abs(to_number(value))


def int_(value):
    if _is_null(value):
        return None
    return int(basic_number(value))


def mod(dividend, divisor):
    """Remainder with the sign of the dividend (C and BASIC semantics)."""
    if _any_null(dividend, divisor):
        return None
    a, b = _pair(basic_number(dividend), basic_number(divisor))
    if b == 0:
        raise RowError("modulo by zero")
    if isinstance(a, int) and isinstance(b, int):
        remainder = abs(a) % abs(b)
        return remainder if a >= 0 else -remainder
    if isinstance(a, float) or isinstance(b, float):
        return _math.fmod(a, b)
    return Decimal(a) % Decimal(b)


def rem(dividend, divisor):
    return mod(dividend, divisor)


def div(dividend, divisor):
    """Div: the whole part of the real division."""
    if _any_null(dividend, divisor):
        return None
    b = float(to_number(divisor))
    if b == 0:
        raise RowError("division by zero")
    return float(int(float(to_number(dividend)) / b))


def sqrt(value):
    return None if _is_null(value) else _math.sqrt(float(to_number(value)))


def exp(value):
    return None if _is_null(value) else _math.exp(float(to_number(value)))


def ln(value):
    return None if _is_null(value) else _math.log(float(to_number(value)))


def log10(value):
    return None if _is_null(value) else _math.log10(float(to_number(value)))


def rand():
    return _random.randint(0, 2 ** 32 - 1)


def random(limit=None):
    if limit is None:
        return _random.randint(0, 2 ** 32 - 1)
    return _random.randint(0, max(int(to_number(limit)) - 1, 0))


def rnd(limit):
    if _is_null(limit):
        return None
    n = int(basic_number(limit))
    return _random.randint(0, n - 1) if n > 0 else 0


def ceil(value):
    return None if _is_null(value) else int(_math.ceil(to_number(value)))


def floor(value):
    return None if _is_null(value) else int(_math.floor(to_number(value)))


def sin(value):
    return None if _is_null(value) else _math.sin(float(to_number(value)))


def cos(value):
    return None if _is_null(value) else _math.cos(float(to_number(value)))


def tan(value):
    return None if _is_null(value) else _math.tan(float(to_number(value)))


def asin(value):
    return None if _is_null(value) else _math.asin(float(to_number(value)))


def acos(value):
    return None if _is_null(value) else _math.acos(float(to_number(value)))


def atan(value):
    return None if _is_null(value) else _math.atan(float(to_number(value)))


def max_(a, b):
    if _any_null(a, b):
        return None
    x, y = _typed_pair(a, b)
    return x if x >= y else y


def min_(a, b):
    if _any_null(a, b):
        return None
    x, y = _typed_pair(a, b)
    return x if x <= y else y


def bit_and(a, b):
    return None if _any_null(a, b) else int(to_number(a)) & int(to_number(b))


def bit_or(a, b):
    return None if _any_null(a, b) else int(to_number(a)) | int(to_number(b))


def bit_xor(a, b):
    return None if _any_null(a, b) else int(to_number(a)) ^ int(to_number(b))


def set_bit_on(value, bit):
    return None if _any_null(value, bit) else int(to_number(value)) | (1 << int(to_number(bit)))


def set_bit_off(value, bit):
    return None if _any_null(value, bit) else int(to_number(value)) & ~(1 << int(to_number(bit)))


def get_environment(name):
    if _is_null(name):
        return None
    return _os.environ.get(to_str(name), "")
