"""Files, data sets, hashed files, databases and stage operations for jobs generated by ds2af.

Frames hold Python objects (dtype object) and None for SQL NULL, so values keep the exact types the
DataStage metadata declares: int, Decimal, float, str, datetime.date/time/datetime. Joins and lookups
are hash joins over dict rows: null keys never match, and numbers match numeric strings the way
DataStage's implicit conversions do.
"""

from __future__ import annotations

import csv
import glob as _glob
import os
import pickle
import subprocess
import sys
from decimal import ROUND_DOWN, Decimal, InvalidOperation

import pandas as pd

from . import dsfunc as F
from .dsfunc import NotTranslated, RowError, to_str

ENCODING = os.environ.get("DS2AF_ENCODING", "utf-8")
ENCODING_ERRORS = "surrogateescape"


class Col:
    """Column metadata: name and logical type (string, integer, decimal, float, date, time, timestamp, binary)."""

    __slots__ = ("name", "type", "length", "scale", "nullable", "key", "fixed")

    def __init__(self, name, type="string", length=0, scale=0, nullable=True, key=False, fixed=False):
        self.name = name
        self.type = type
        self.length = length
        self.scale = scale
        self.nullable = nullable
        self.key = key
        self.fixed = fixed

    def __repr__(self):
        return "Col(%r, %r)" % (self.name, self.type)


def names(columns):
    return [c.name for c in columns]


def not_converted(stage, reason):
    """Placeholder for a stage the migrator could not convert; fails the job when reached."""
    raise NotTranslated("stage %s was not converted: %s" % (stage, reason))


# --------------------------------------------------------------------------- frames and rows

def _clean(value):
    return None if F._is_null(value) else value


def rows(frame):
    """The rows of a frame as dicts; pandas missing values become None."""
    if frame is None or len(frame) == 0:
        return
    columns = list(frame.columns)
    for values in frame.itertuples(index=False, name=None):
        yield {c: _clean(v) for c, v in zip(columns, values)}


def empty(columns):
    return pd.DataFrame(columns=names(columns), dtype=object)


def coerce(col, value):
    """Converts a value to the column's declared type; leaves it unchanged when it does not convert."""
    if F._is_null(value):
        return None
    t = col.type
    try:
        if t == "string":
            return value if isinstance(value, str) else to_str(value)
        if t == "integer":
            if isinstance(value, bool):
                return int(value)
            if isinstance(value, int):
                return value
            number = F.to_number(value)
            return int(number) if number == int(number) else value
        if t == "decimal":
            number = value if isinstance(value, Decimal) else Decimal(to_str(value).strip() or "0")
            if col.scale or col.length:
                number = number.quantize(Decimal(1).scaleb(-col.scale), rounding=ROUND_DOWN)
            return number
        if t == "float":
            return value if isinstance(value, float) else float(F.to_number(value))
        if t == "date":
            return F.string_to_date(value)
        if t == "time":
            return F.string_to_time(value)
        if t == "timestamp":
            return F.string_to_timestamp(value)
    except (RowError, InvalidOperation, ValueError, TypeError):
        return value
    return value


def frame(records, columns, typed=True):
    """A frame with exactly the link's columns, in order, values coerced to the declared types."""
    cols = names(columns)
    if typed:
        records = [{c.name: coerce(c, r.get(c.name)) for c in columns} for r in records]
    else:
        records = [{c: r.get(c) for c in cols} for r in records]
    if not records:
        return empty(columns)
    return pd.DataFrame(records, columns=cols, dtype=object)


def project(ctx, source, mapping, columns, typed=True):
    """Selects and renames columns: mapping is a list of (output column, input column)."""
    out = []
    for row in rows(source):
        out.append({target: row.get(src) for target, src in mapping})
    return frame(out, columns, typed)


# --------------------------------------------------------------------------- text conversion

def _parse_field(col, text, formats, typed):
    if not typed or col.type == "string":
        return text
    stripped = text.strip()
    if stripped == "":
        return None
    t = col.type
    if t == "integer":
        number = F._parse_number(stripped)
        if isinstance(number, int):
            return number
        if isinstance(number, Decimal) and number == int(number):
            return int(number)
        raise RowError("column %s: %r is not an integer" % (col.name, text))
    if t == "decimal":
        try:
            return Decimal(stripped)
        except InvalidOperation:
            raise RowError("column %s: %r is not a decimal" % (col.name, text))
    if t == "float":
        try:
            return float(stripped)
        except ValueError:
            raise RowError("column %s: %r is not a number" % (col.name, text))
    if t == "date":
        return F.string_to_date(stripped, formats.get("date"))
    if t == "time":
        return F.string_to_time(stripped, formats.get("time"))
    if t == "timestamp":
        return F.string_to_timestamp(stripped, formats.get("timestamp"))
    return text


def _format_decimal(col, value, padding):
    number = value if isinstance(value, Decimal) else Decimal(to_str(value))
    scale = col.scale or 0
    if scale:
        number = number.quantize(Decimal(1).scaleb(-scale), rounding=ROUND_DOWN)
    text = format(abs(number), "f")
    if padding and col.length:
        whole, _, fraction = text.partition(".")
        whole = whole.rjust(max(col.length - scale, 1), "0")
        text = whole + ("." + fraction if fraction else "")
    return ("-" + text) if number < 0 else text


def _format_field(col, value, formats, null_value, decimal_padding, typed=True):
    if F._is_null(value):
        return null_value
    if not typed:
        return to_str(value)
    t = col.type
    if t == "string":
        text = to_str(value)
        return text.ljust(col.length) if col.fixed and col.length else text
    if t == "decimal":
        return _format_decimal(col, value, decimal_padding)
    if t == "date" and formats.get("date"):
        return F.date_to_string(value, formats["date"])
    if t == "time" and formats.get("time"):
        return F.time_to_string(value, formats["time"])
    if t == "timestamp" and formats.get("timestamp"):
        return F.timestamp_to_string(value, formats["timestamp"])
    return to_str(value)


# --------------------------------------------------------------------------- sequential files

def _expand_paths(paths):
    result = []
    for path in paths if isinstance(paths, (list, tuple)) else [paths]:
        if path is None:
            continue
        if any(ch in path for ch in "*?["):
            result.extend(sorted(_glob.glob(path)))
        else:
            result.append(path)
    return result


def _split_records(handle, delimiter, quote, record_delimiter):
    if record_delimiter not in (None, "\n", "\r\n"):
        content = handle.read()
        for record in content.split(record_delimiter):
            if record:
                yield _split_fields(record, delimiter, quote)
        return
    if delimiter is not None and len(delimiter) == 1:
        reader = csv.reader(handle, delimiter=delimiter, quotechar=quote or '"',
                            quoting=csv.QUOTE_MINIMAL if quote else csv.QUOTE_NONE, doublequote=True)
        for record in reader:
            yield record
        return
    for line in handle:
        line = line.rstrip("\r\n")
        yield _split_fields(line, delimiter, quote)


def _split_fields(line, delimiter, quote):
    if delimiter is None:
        return [line]
    if not quote:
        return line.split(delimiter)
    fields, current, inside, i = [], [], False, 0
    while i < len(line):
        if line.startswith(quote, i):
            if inside and line.startswith(quote, i + len(quote)):
                current.append(quote)
                i += 2 * len(quote)
                continue
            inside = not inside
            i += len(quote)
            continue
        if not inside and line.startswith(delimiter, i):
            fields.append("".join(current))
            current = []
            i += len(delimiter)
            continue
        current.append(line[i])
        i += 1
    fields.append("".join(current))
    return fields


def _fixed_fields(line, columns):
    fields, position = [], 0
    for col in columns:
        width = col.length or 1
        fields.append(line[position:position + width])
        position += width
    return fields


def read_delimited(ctx, paths, columns, delimiter=",", quote='"', header=False, null_value=None, typed=True,
                   final_delimiter=False, fixed_width=False, record_delimiter="\n", reject=False,
                   reject_mode="continue", missing="error", encoding=None, date_format=None,
                   time_format=None, timestamp_format=None, stage="Sequential File"):
    """Reads delimited or fixed-width text. Rows that do not fit the metadata go to the reject link
    (reject=True), abort the job (reject_mode="fail") or are dropped with a warning."""
    formats = {"date": date_format, "time": time_format, "timestamp": timestamp_format}
    out, rejected = [], []
    count = len(columns)
    for path in _expand_paths(paths):
        if not os.path.exists(path):
            if missing in ("okay", "ok", "depends"):
                ctx.warn("%s: file %s not found, treated as empty" % (stage, path))
                continue
            ctx.abort("%s: file %s not found" % (stage, path))
        with open(path, "r", encoding=encoding or ENCODING, errors=ENCODING_ERRORS, newline="") as handle:
            if fixed_width:
                records = ([line.rstrip("\r\n")] for line in handle)
            else:
                records = _split_records(handle, delimiter, quote, record_delimiter)
            number = 0
            for record in records:
                number += 1
                if header and number == 1:
                    continue
                if fixed_width:
                    if record[0] == "":
                        continue
                    fields = _fixed_fields(record[0], columns)
                else:
                    fields = record
                    if final_delimiter and len(fields) == count + 1 and fields[-1] == "":
                        fields = fields[:-1]
                    if len(fields) == 1 and fields[0] == "" and count != 1:
                        continue
                try:
                    if len(fields) != count:
                        raise RowError("%d field(s) found, %d expected" % (len(fields), count))
                    values = {}
                    for col, text in zip(columns, fields):
                        values[col.name] = None if null_value is not None and text == null_value else _parse_field(col, text, formats, typed)
                    out.append(values)
                except RowError as exc:
                    raw = (delimiter or "").join(fields)
                    if reject:
                        rejected.append({"rejected": raw})
                    elif reject_mode == "fail":
                        ctx.abort("%s: %s line %d: %s" % (stage, path, number, exc))
                    else:
                        ctx.reject(stage, "%s:%d" % (os.path.basename(path), number), exc)
    result = pd.DataFrame(out, columns=names(columns), dtype=object) if out else empty(columns)
    if reject:
        return result, pd.DataFrame(rejected, columns=["rejected"], dtype=object)
    return result


def write_delimited(ctx, source, path, columns, delimiter=",", quote='"', header=False, null_value="", append=False,
                    final_delimiter=False, fixed_width=False, typed=True, decimal_padding=True, line_end="\n",
                    encoding=None, date_format=None, time_format=None, timestamp_format=None, stage="Sequential File"):
    """Writes a frame as delimited or fixed-width text (quotes around string columns when quote is set)."""
    formats = {"date": date_format, "time": time_format, "timestamp": timestamp_format}
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
    mode = "a" if append and os.path.exists(path) else "w"
    written = 0
    with open(path, mode, encoding=encoding or ENCODING, errors=ENCODING_ERRORS, newline="") as handle:
        if header and mode == "w":
            handle.write(_join([c.name for c in columns], [False] * len(columns), delimiter, quote, final_delimiter) + line_end)
        quoted = [c.type == "string" for c in columns]
        for row in rows(source):
            fields = [_format_field(c, row.get(c.name), formats, null_value, decimal_padding, typed) for c in columns]
            if fixed_width:
                handle.write("".join(f.ljust(c.length or len(f))[:c.length or len(f)] for c, f in zip(columns, fields)) + line_end)
            else:
                nulls = [F._is_null(row.get(c.name)) for c in columns]
                handle.write(_join(fields, [q and not n for q, n in zip(quoted, nulls)], delimiter, quote, final_delimiter) + line_end)
            written += 1
    ctx.info("%s: %d row(s) written to %s", stage, written, path)
    return written


def _join(fields, quoted, delimiter, quote, final_delimiter):
    parts = []
    for text, q in zip(fields, quoted):
        if quote and q:
            parts.append(quote + text.replace(quote, quote + quote) + quote)
        else:
            parts.append(text)
    line = (delimiter or "").join(parts)
    return line + (delimiter or "") if final_delimiter else line


# --------------------------------------------------------------------------- data sets and hashed files

def _dataset_path(path):
    return path


def read_dataset(ctx, path, columns, stage="Data Set"):
    """Data sets are stored as pickled frames at the data set's path."""
    target = _dataset_path(path)
    if not os.path.exists(target):
        ctx.abort("%s: data set %s not found" % (stage, target))
    with open(target, "rb") as handle:
        stored = pickle.load(handle)
    return frame(list(rows(stored)), columns)


def write_dataset(ctx, source, path, columns, mode="overwrite", stage="Data Set"):
    target = _dataset_path(path)
    directory = os.path.dirname(target)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
    data = frame(list(rows(source)), columns)
    if mode == "append" and os.path.exists(target):
        with open(target, "rb") as handle:
            data = pd.concat([pickle.load(handle), data], ignore_index=True)
    elif mode == "create" and os.path.exists(target):
        ctx.abort("%s: data set %s already exists" % (stage, target))
    with open(target, "wb") as handle:
        pickle.dump(data, handle)
    ctx.info("%s: %d row(s) written to %s", stage, len(data), target)
    return len(data)


def _hashed_path(name, directory):
    base = directory or os.environ.get("DS2AF_HASHED_DIR", "hashed")
    return os.path.join(base, name + ".hashed.pkl")


def read_hashed(ctx, name, directory, columns, stage="Hashed File"):
    path = _hashed_path(name, directory)
    if not os.path.exists(path):
        ctx.abort("%s: hashed file %s not found (%s)" % (stage, name, path))
    with open(path, "rb") as handle:
        stored = pickle.load(handle)
    return frame(list(rows(stored)), columns, typed=False)


def write_hashed(ctx, source, name, directory, columns, clear=False, stage="Hashed File"):
    """Hashed files are keyed: writing a row whose key exists replaces the stored row."""
    path = _hashed_path(name, directory)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    keys = [c.name for c in columns if c.key] or [columns[0].name]
    stored = {}
    if not clear and os.path.exists(path):
        with open(path, "rb") as handle:
            for row in rows(pickle.load(handle)):
                stored[tuple(to_str(row.get(k)) for k in keys)] = row
    for row in rows(source):
        stored[tuple(to_str(row.get(k)) for k in keys)] = {c.name: row.get(c.name) for c in columns}
    data = frame(list(stored.values()), columns, typed=False)
    with open(path, "wb") as handle:
        pickle.dump(data, handle)
    ctx.info("%s: %d row(s) in hashed file %s", stage, len(data), name)
    return len(data)


# --------------------------------------------------------------------------- keys, lookups and joins

def _norm(value):
    if isinstance(value, bool):
        return str(int(value))
    if isinstance(value, (int, float, Decimal)):
        number = Decimal(str(value)) if not isinstance(value, Decimal) else value
        text = format(number.normalize(), "f") if number == number else "nan"
        return text[:-2] if text.endswith(".0") else text
    if isinstance(value, str):
        return value
    return to_str(value)


def key_of(row, columns):
    """Normalised key tuple; None when any key value is null (null keys never match)."""
    key = []
    for c in columns:
        value = row.get(c)
        if F._is_null(value):
            return None
        key.append(_norm(value))
    return tuple(key)


def lookup_key(*values):
    """Key tuple for a transformer reference lookup; None when a key value is null."""
    key = []
    for value in values:
        if F._is_null(value):
            return None
        key.append(_norm(value))
    return tuple(key)


def index(source, keys):
    """Dict of key tuple to row for transformer reference links; the first row of a key wins."""
    result = {}
    for row in rows(source):
        k = key_of(row, keys)
        if k is not None and k not in result:
            result[k] = row
    return result


def lookup(ctx, stage, stream, refs, mapping, columns, reject=False, reject_columns=None):
    """Lookup stage. refs: dicts with frame, keys [(stream col, ref col)], on_fail
    (continue/drop/fail/reject) and multiple. mapping: (output col, input position, input col);
    position 0 is the stream, 1.. the references in order."""
    indexes = []
    for ref in refs:
        idx = {}
        duplicates = 0
        ref_keys = [rc for _, rc in ref["keys"]]
        for r in rows(ref["frame"]):
            k = key_of(r, ref_keys)
            if k is None:
                continue
            bucket = idx.setdefault(k, [])
            if bucket and not ref.get("multiple"):
                duplicates += 1
                continue
            bucket.append(r)
        if duplicates:
            ctx.warn("%s: %d duplicate key(s) in reference %s ignored" % (stage, duplicates, ref.get("name", "?")))
        indexes.append(idx)

    out, rejected = [], []
    number = 0
    for row in rows(stream):
        number += 1
        combos = [[row]]
        outcome = None
        for i, ref in enumerate(refs):
            k = key_of(row, [sc for sc, _ in ref["keys"]])
            matches = indexes[i].get(k) if k is not None else None
            if matches and ref.get("condition") is not None and not ref["condition"](row):
                matches = None
                mode = ref.get("condition_not_met", ref.get("on_fail", "fail"))
            else:
                mode = ref.get("on_fail", "fail")
            if not matches:
                if mode == "continue":
                    matches = [None]
                elif mode == "drop":
                    outcome = "drop"
                    break
                elif mode == "reject":
                    outcome = "reject"
                    break
                else:
                    ctx.abort("%s: lookup failed in %s for row %d (key %r)" % (stage, ref.get("name", "?"), number, k))
            combos = [c + [m] for c in combos for m in matches]
        if outcome == "drop":
            continue
        if outcome == "reject":
            if reject:
                rejected.append(row)
            else:
                ctx.reject(stage, number, "lookup failed")
            continue
        for combo in combos:
            out.append({name: (combo[position] or {}).get(col) for name, position, col in mapping})
    result = frame(out, columns)
    if reject:
        return result, frame(rejected, reject_columns or [Col(c) for c in stream.columns])
    return result


def join(ctx, stage, how, inputs, keys, mapping, columns):
    """Join stage (inner, leftouter, rightouter, fullouter) on key columns present in every input."""
    how = how.lower().replace("join", "").replace("_", "")
    current = [[r] for r in rows(inputs[0])]
    for position in range(1, len(inputs)):
        right_rows = list(rows(inputs[position]))
        idx = {}
        for r in right_rows:
            k = key_of(r, keys)
            if k is not None:
                idx.setdefault(k, []).append(r)
        matched_right = set()
        joined = []
        for combo in current:
            left = next((c for c in combo if c is not None), {})
            k = key_of(left, keys)
            matches = idx.get(k) if k is not None else None
            if matches:
                for r in matches:
                    matched_right.add(id(r))
                    joined.append(combo + [r])
            elif how in ("leftouter", "fullouter"):
                joined.append(combo + [None])
        if how in ("rightouter", "fullouter"):
            for r in right_rows:
                if id(r) not in matched_right:
                    joined.append([None] * position + [r])
        current = joined
    out = []
    for combo in current:
        out.append({name: (combo[position] or {}).get(col) for name, position, col in mapping})
    return frame(out, columns)


def merge(ctx, stage, master, updates, keys, mapping, columns, unmatched_masters="keep", reject_columns=None):
    """Merge stage: master rows combined with the first matching row of each update link.
    Returns the output frame followed by one reject frame per update link."""
    indexes = []
    for update in updates:
        idx = {}
        for r in rows(update):
            k = key_of(r, keys)
            if k is not None and k not in idx:
                idx[k] = r
        indexes.append(idx)
    used = [set() for _ in updates]
    out = []
    for row in rows(master):
        k = key_of(row, keys)
        combo = [row]
        matched_all = True
        for i, idx in enumerate(indexes):
            match = idx.get(k) if k is not None else None
            if match is None:
                matched_all = False
            else:
                used[i].add(k)
            combo.append(match)
        if not matched_all and unmatched_masters == "drop":
            continue
        out.append({name: (combo[position] or {}).get(col) for name, position, col in mapping})
    rejects = []
    for i, update in enumerate(updates):
        unmatched = [r for r in rows(update) if key_of(r, keys) not in used[i]]
        cols = (reject_columns or [None] * len(updates))[i] or [Col(c) for c in update.columns]
        rejects.append(frame(unmatched, cols))
    return [frame(out, columns)] + rejects


# --------------------------------------------------------------------------- reshaping stages

def _aggregate(function, values, group_size):
    f = function.lower()
    if f in ("count", "nvalues"):
        return len(values)
    if f in ("missing", "nmissing"):
        return group_size - len(values)
    if f == "nrecs":
        return group_size
    if not values:
        return None
    if f == "first":
        return values[0]
    if f == "last":
        return values[-1]
    if f in ("max", "min"):
        best = values[0]
        for v in values[1:]:
            a, b = F._typed_pair(v, best)
            if (a > b) if f == "max" else (a < b):
                best = v
        return best
    numbers = [F.to_number(v) for v in values]
    if f == "sum":
        total = numbers[0]
        for n in numbers[1:]:
            total, n = F._pair(total, n)
            total = total + n
        return total
    floats = [float(n) for n in numbers]
    count_ = len(floats)
    mean = sum(floats) / count_
    if f == "mean":
        return mean
    if f == "range":
        return max(floats) - min(floats)
    css = sum((x - mean) ** 2 for x in floats)
    if f == "css":
        return css
    if f == "uss":
        return sum(x * x for x in floats)
    variance = css / (count_ - 1) if count_ > 1 else 0.0
    if f == "var":
        return variance
    if f == "std":
        return variance ** 0.5
    if f == "ste":
        return (variance ** 0.5) / (count_ ** 0.5)
    if f == "cv":
        return (variance ** 0.5) / mean * 100 if mean else None
    raise NotTranslated("aggregate function %s is not supported" % function)


def aggregate(ctx, stage, source, keys, calculations, columns, count_field=None, sort_output=False):
    """Aggregator stage: group by keys (a name, or (input, output) to rename); calculations are
    (input col, function, output col)."""
    key_inputs = [k[0] if isinstance(k, tuple) else k for k in keys]
    key_outputs = [k[1] if isinstance(k, tuple) else k for k in keys]
    groups = {}
    for row in rows(source):
        groups.setdefault(tuple(row.get(k) for k in key_inputs), []).append(row)
    ordered = list(groups.items())
    if sort_output:
        ordered = _sorted_items(ordered)
    out = []
    for key, group in ordered:
        record = dict(zip(key_outputs, key))
        if count_field:
            record[count_field] = len(group)
        for input_col, function, output_col in calculations:
            values = [r.get(input_col) for r in group if not F._is_null(r.get(input_col))]
            record[output_col] = _aggregate(function, values, len(group))
        out.append(record)
    return frame(out, columns)


def _sorted_items(items):
    def rank(value):
        return (0, 0) if value is None else (1, value)
    return sorted(items, key=lambda kv: tuple(rank(v) for v in kv[0]))


class SortKey:
    __slots__ = ("column", "ascending", "nulls_first", "case_sensitive")

    def __init__(self, column, ascending=True, nulls_first=True, case_sensitive=True):
        self.column = column
        self.ascending = ascending
        self.nulls_first = nulls_first
        self.case_sensitive = case_sensitive


def _sort_rows(data, keys):
    for key in reversed(keys):
        reverse = not key.ascending
        null_rank = 0 if key.nulls_first != reverse else 2

        def sort_value(row, key=key, null_rank=null_rank):
            value = row.get(key.column)
            if F._is_null(value):
                return (null_rank, 0)
            if isinstance(value, str) and not key.case_sensitive:
                value = value.lower()
            return (1, value)

        data.sort(key=sort_value, reverse=reverse)
    return data


def sort(ctx, stage, source, keys, columns, unique=False, key_change_column=None):
    """Sort stage: stable multi-key sort with per-key direction, null position and case sensitivity."""
    data = _sort_rows(list(rows(source)), keys)
    if unique or key_change_column:
        out = []
        previous = object()
        for row in data:
            k = tuple(row.get(key.column) if key.case_sensitive or not isinstance(row.get(key.column), str)
                      else row.get(key.column).lower() for key in keys)
            changed = k != previous
            previous = k
            if unique and not changed:
                continue
            if key_change_column:
                row = dict(row)
                row[key_change_column] = 1 if changed else 0
            out.append(row)
        data = out
    return frame(data, columns)


def remove_duplicates(ctx, stage, source, keys, columns, keep="first", case_sensitive=None):
    """Remove Duplicates stage: drops adjacent rows with equal keys (the input is expected sorted)."""
    sensitive = case_sensitive or [True] * len(keys)
    out = []
    previous = object()
    for row in rows(source):
        k = tuple(row.get(c).lower() if isinstance(row.get(c), str) and not s else row.get(c) for c, s in zip(keys, sensitive))
        if k != previous:
            out.append(row)
        elif keep == "last":
            out[-1] = row
        previous = k
    return frame(out, columns)


def funnel(ctx, stage, inputs, columns, sort_keys=None):
    """Funnel stage: continuous or sequence funnels concatenate; a sort funnel merges by key."""
    data = []
    for source in inputs:
        data.extend(rows(source))
    if sort_keys:
        data = _sort_rows(data, sort_keys)
    return frame(data, columns)


def filter_rows(ctx, stage, source, predicates, output_columns, first_only=False, reject_columns=None):
    """Filter stage: predicates[i] decides membership of output i. Returns the output frames plus,
    when reject_columns is given, a frame of rows that matched no predicate."""
    outputs = [[] for _ in predicates]
    rejected = []
    number = 0
    for row in rows(source):
        number += 1
        matched = False
        for i, predicate in enumerate(predicates):
            try:
                accepted = F.truth(predicate(row))
            except RowError as exc:
                ctx.reject(stage, number, exc)
                accepted = False
            if accepted:
                outputs[i].append(row)
                matched = True
                if first_only:
                    break
        if not matched:
            rejected.append(row)
    result = [frame(o, cols) for o, cols in zip(outputs, output_columns)]
    if reject_columns is not None:
        result.append(frame(rejected, reject_columns))
    return result


def switch_rows(ctx, stage, source, selector, cases, output_columns, default_output=None, if_not_found="drop"):
    """Switch stage: cases maps selector values (as text) to output positions."""
    outputs = [[] for _ in output_columns]
    number = 0
    for row in rows(source):
        number += 1
        value = row.get(selector)
        target = cases.get(_norm(value)) if not F._is_null(value) else None
        if target is None:
            target = default_output
        if target is None:
            if if_not_found == "fail":
                ctx.abort("%s: no case for selector value %r" % (stage, value))
            ctx.reject(stage, number, "no case for selector value %r" % (value,))
            continue
        outputs[target].append(row)
    return [frame(o, cols) for o, cols in zip(outputs, output_columns)]


def head(ctx, stage, source, count, columns, skip=0):
    return frame(list(rows(source))[skip:skip + count], columns)


def tail(ctx, stage, source, count, columns):
    data = list(rows(source))
    return frame(data[-count:] if count else [], columns)


def sample(ctx, stage, source, columns, percent=None, period=None, max_rows=None):
    data = list(rows(source))
    if period:
        data = data[::max(int(period), 1)]
    elif percent is not None:
        step = max(int(round(100.0 / max(float(percent), 0.0001))), 1)
        data = data[::step]
    if max_rows:
        data = data[:max_rows]
    return frame(data, columns)


def peek(ctx, stage, source, count=10):
    """Peek stage: logs the first rows."""
    for i, row in enumerate(rows(source)):
        if i >= count:
            break
        ctx.info("%s: %s", stage, row)
    return source


def partition(ctx, stage, source, outputs):
    """Link Partitioner: deals rows round-robin to the outputs."""
    parts = [[] for _ in range(outputs)]
    for i, row in enumerate(rows(source)):
        parts[i % outputs].append(row)
    return [pd.DataFrame(p, columns=list(source.columns), dtype=object) for p in parts]


def surrogate_key(ctx, stage, source, column, columns, start=1):
    out = []
    for i, row in enumerate(rows(source)):
        row = dict(row)
        row[column] = start + i
        out.append(row)
    return frame(out, columns)


def generate_rows(ctx, stage, count, columns):
    """Row Generator: rows with integers counting from 0 and empty strings (DataStage's default cycle)."""
    out = []
    for i in range(int(count)):
        record = {}
        for col in columns:
            if col.type in ("integer", "decimal", "float"):
                record[col.name] = i
            elif col.type == "string":
                record[col.name] = ""
            else:
                record[col.name] = None
        out.append(record)
    return frame(out, columns)


def change_capture(ctx, stage, before, after, keys, values, columns, code_column="change_code",
                   drop=(), codes=(0, 1, 2, 3)):
    """Change Capture: compares before and after rows by key; the code column holds copy (0),
    insert (1), delete (2) or edit (3). Codes named in drop are not output."""
    copy_code, insert_code, delete_code, edit_code = codes
    before_index = {}
    for row in rows(before):
        before_index.setdefault(key_of(row, keys), row)
    after_keys = set()
    out = []
    for row in rows(after):
        k = key_of(row, keys)
        after_keys.add(k)
        old = before_index.get(k)
        if old is None:
            code = insert_code
        elif any(_norm(old.get(v)) != _norm(row.get(v)) if not (F._is_null(old.get(v)) and F._is_null(row.get(v))) else False
                 for v in values):
            code = edit_code
        else:
            code = copy_code
        if code not in drop:
            record = dict(row)
            record[code_column] = code
            out.append(record)
    if delete_code not in drop:
        for k, row in before_index.items():
            if k not in after_keys:
                record = dict(row)
                record[code_column] = delete_code
                out.append(record)
    out = _sort_rows(out, [SortKey(k) for k in keys])
    return frame(out, columns)


# --------------------------------------------------------------------------- databases

def _airflow_connection(conn_id):
    try:
        from airflow.hooks.base import BaseHook
    except ImportError:
        try:
            from airflow.sdk import BaseHook
        except ImportError:
            return None
    return BaseHook.get_connection(conn_id).get_hook()


def connect(conn_id):
    """A DB-API connection for an Airflow connection id. DS2AF_CONN_<ID>=sqlite:///path overrides
    it (useful for tests and local runs)."""
    url = os.environ.get("DS2AF_CONN_" + conn_id.upper().replace("-", "_"))
    if url:
        if url.startswith("sqlite:///"):
            import sqlite3
            return sqlite3.connect(url[len("sqlite:///"):])
        try:
            import sqlalchemy
        except ImportError:
            raise NotTranslated("connection %s: install SQLAlchemy to use %s" % (conn_id, url))
        return sqlalchemy.create_engine(url).raw_connection()
    hook = _airflow_connection(conn_id)
    if hook is None:
        raise NotTranslated("connection %s is not configured (Airflow connection or DS2AF_CONN_%s)" % (conn_id, conn_id.upper()))
    return hook.get_conn()


def _paramstyle(connection):
    module = sys.modules.get(type(connection).__module__.split(".")[0])
    return getattr(module, "paramstyle", "qmark")


def _placeholders(connection, count, names_=None):
    style = _paramstyle(connection)
    if style == "named":
        return [":%s" % (n or "p%d" % i) for i, n in enumerate(names_ or [None] * count)]
    if style in ("format", "pyformat"):
        return ["%s"] * count
    if style == "numeric":
        return [":%d" % (i + 1) for i in range(count)]
    return ["?"] * count


def read_sql(ctx, conn_id, sql, columns, stage="Database"):
    """Runs a query; result columns are matched to the link's columns by name, else by position."""
    connection = connect(conn_id)
    try:
        cursor = connection.cursor()
        cursor.execute(sql)
        described = [d[0] for d in cursor.description]
        fetched = cursor.fetchall()
    finally:
        connection.close()
    wanted = names(columns)
    lower = [d.lower() for d in described]
    if all(w.lower() in lower for w in wanted):
        positions = [lower.index(w.lower()) for w in wanted]
    elif len(described) == len(wanted):
        positions = list(range(len(wanted)))
    else:
        ctx.abort("%s: query returned columns %s, link expects %s" % (stage, described, wanted))
    out = [{w: record[p] for w, p in zip(wanted, positions)} for record in fetched]
    ctx.info("%s: %d row(s) read", stage, len(out))
    return frame(out, columns)


def _db_value(value):
    if F._is_null(value):
        return None
    if isinstance(value, Decimal):
        return str(value)
    return value


def write_table(ctx, source, conn_id, table, columns, mode="append", keys=None, sql=None, stage="Database"):
    """Writes rows: append, truncate (delete all, then insert), replace, update, upsert
    (update, else insert), insert_update (insert, else update), delete, or user SQL with
    ORCHESTRATE.column placeholders."""
    connection = connect(conn_id)
    cols = names(columns)
    keys = keys or [c.name for c in columns if c.key]
    data = [[_db_value(row.get(c)) for c in cols] for row in rows(source)]
    written = 0
    try:
        cursor = connection.cursor()
        if mode in ("truncate", "replace", "clear"):
            cursor.execute("DELETE FROM %s" % table)
        if sql:
            import re
            fields = re.findall(r"ORCHESTRATE\.(\w+)", sql, flags=re.IGNORECASE)
            marks = _placeholders(connection, len(fields), fields)
            statement = sql
            for field_name, mark in zip(fields, marks):
                statement = re.sub(r"ORCHESTRATE\.%s\b" % re.escape(field_name), mark, statement, count=1, flags=re.IGNORECASE)
            params = [[_db_value(row.get(f)) for f in fields] for row in rows(source)]
            if _paramstyle(connection) == "named":
                params = [dict(zip(fields, p)) for p in params]
            cursor.executemany(statement, params)
            written = len(params)
        else:
            insert = "INSERT INTO %s (%s) VALUES (%s)" % (table, ", ".join(cols), ", ".join(_placeholders(connection, len(cols), cols)))
            non_keys = [c for c in cols if c not in keys]
            update = None
            if keys and non_keys:
                sets = ", ".join("%s = %s" % (c, m) for c, m in zip(non_keys, _placeholders(connection, len(non_keys), non_keys)))
                where = " AND ".join("%s = %s" % (k, m) for k, m in zip(keys, _placeholders(connection, len(keys), keys)))
                update = "UPDATE %s SET %s WHERE %s" % (table, sets, where)
            for values in data:
                record = dict(zip(cols, values))
                if mode in ("update", "upsert", "update_insert") and update:
                    cursor.execute(update, _bind(connection, [record[c] for c in non_keys + keys], non_keys + keys))
                    if cursor.rowcount == 0 and mode != "update":
                        cursor.execute(insert, _bind(connection, values, cols))
                elif mode == "insert_update" and update:
                    try:
                        cursor.execute(insert, _bind(connection, values, cols))
                    except Exception:
                        cursor.execute(update, _bind(connection, [record[c] for c in non_keys + keys], non_keys + keys))
                elif mode == "delete" and keys:
                    where = " AND ".join("%s = %s" % (k, m) for k, m in zip(keys, _placeholders(connection, len(keys), keys)))
                    cursor.execute("DELETE FROM %s WHERE %s" % (table, where), _bind(connection, [record[k] for k in keys], keys))
                else:
                    cursor.execute(insert, _bind(connection, values, cols))
                written += 1
        connection.commit()
    finally:
        connection.close()
    ctx.info("%s: %d row(s) written to %s", stage, written, table)
    return written


def _bind(connection, values, names_):
    if _paramstyle(connection) == "named":
        return dict(zip(names_, values))
    return values


# --------------------------------------------------------------------------- before/after subroutines

def exec_subroutine(ctx, name, argument):
    """Before/after-job subroutines ExecSH, ExecSHSilent, ExecDOS and ExecDOSSilent."""
    routine = (name or "").split(".")[-1].upper()
    if routine not in ("EXECSH", "EXECSHSILENT", "EXECDOS", "EXECDOSSILENT", "EXECTCL"):
        raise NotTranslated("before/after subroutine %s has no Python implementation" % name)
    completed = subprocess.run(argument, shell=True, capture_output=True, text=True)
    if not routine.endswith("SILENT"):
        ctx.info("%s %s: %s", name, argument, (completed.stdout + completed.stderr).strip())
    if completed.returncode != 0:
        ctx.abort("%s %r returned %d" % (name, argument, completed.returncode))
    return completed.returncode
