"""Run-time context of a Python job generated by ds2af from a DataStage job."""

from __future__ import annotations

import datetime as _dt
import logging
import os
import re
import socket
from decimal import Decimal, InvalidOperation

from .dsfunc import DSJS, NotTranslated, to_str


class JobAborted(Exception):
    """The job failed: the equivalent of a DataStage job that finished with status Aborted."""


class Param:
    """A job parameter as declared in DataStage (name, type, default value)."""

    __slots__ = ("name", "type", "default", "prompt", "values")

    def __init__(self, name, type="string", default="", prompt="", values=None):
        self.name = name
        self.type = type
        self.default = default
        self.prompt = prompt
        self.values = list(values or [])

    def __repr__(self):
        return "Param(%r, %r, %r)" % (self.name, self.type, self.default)


def _environment_value(name, raw):
    # $PROJDEF (project default) and $ENV both come from the environment of the Airflow worker.
    text = "" if raw is None else str(raw)
    if text == "$UNSET":
        return None
    if text in ("$PROJDEF", "$ENV", ""):
        return os.environ.get(name, "")
    return text


def _convert(param, value):
    if value is None:
        return None
    if param.type == "integer":
        text = str(value).strip()
        if not text:
            return None
        try:
            return int(Decimal(text))
        except InvalidOperation:
            raise JobAborted("parameter %s: %r is not an integer" % (param.name, value))
    if param.type == "float":
        text = str(value).strip()
        if not text:
            return None
        try:
            return Decimal(text)
        except InvalidOperation:
            raise JobAborted("parameter %s: %r is not a number" % (param.name, value))
    return value if isinstance(value, str) else to_str(value)


def resolve_parameters(declared, supplied=None):
    """Typed parameter values: supplied values win over defaults; undeclared values are kept as given."""
    remaining = dict(supplied or {})
    values = {}
    for param in declared:
        raw = remaining.pop(param.name, None)
        if raw is None or (isinstance(raw, str) and raw == "" and param.default not in ("", None)):
            raw = param.default
        if param.name.startswith("$"):
            raw = _environment_value(param.name[1:], raw)
        values[param.name] = _convert(param, raw)
    values.update(remaining)
    return values


_PARAM_REFERENCE = re.compile(r"#([A-Za-z_$][A-Za-z0-9_.$]*)#")


class JobContext:
    """Parameters, #Param# substitution, DataStage macros, link row counts and the resulting job status."""

    MAX_LOGGED_REJECTS = 20

    def __init__(self, job_name, parameters=(), values=None, project=None, invocation_id=None,
                 controller=None, logger=None):
        self.job_name = job_name
        self.project = project or os.environ.get("DS2AF_PROJECT", "")
        self.invocation_id = invocation_id or ""
        self.controller = controller or ""
        self.declared = list(parameters)
        self.params = resolve_parameters(self.declared, values)
        self.started = _dt.datetime.now()
        self.log = logger or logging.getLogger("ds2af.job." + job_name)
        self.warnings = 0
        self.user_status = ""
        self.rows = {}
        self.rejects = {}

    # ---------------------------------------------------------------- parameters and macros

    def param(self, name):
        if name in self.params:
            return self.params[name]
        raise NotTranslated("job %s has no parameter %s" % (self.job_name, name))

    def expand(self, text):
        """Replaces #Param# references, the textual substitution DataStage applies to stage properties."""
        if text is None:
            return None

        def replace(match):
            name = match.group(1)
            if name in self.params:
                value = self.params[name]
                return "" if value is None else to_str(value)
            if name.startswith("$") and name[1:] in os.environ:
                return os.environ[name[1:]]
            self.warn("unknown parameter reference #%s#" % name)
            return match.group(0)

        return _PARAM_REFERENCE.sub(replace, text)

    def macro(self, name):
        key = name.upper()
        if key == "DSJOBNAME":
            return self.job_name
        if key == "DSPROJECTNAME":
            return self.project
        if key == "DSJOBINVOCATIONID":
            return self.invocation_id
        if key == "DSJOBCONTROLLER":
            return self.controller
        if key == "DSHOSTNAME":
            return socket.gethostname()
        if key == "DSJOBSTARTDATE":
            return self.started.strftime("%Y-%m-%d")
        if key == "DSJOBSTARTTIME":
            return self.started.strftime("%H:%M:%S")
        if key == "DSJOBSTARTTIMESTAMP":
            return self.started.strftime("%Y-%m-%d %H:%M:%S")
        if key == "DSJOBWAVENO":
            return 0
        raise NotTranslated("unknown DataStage macro %s" % name)

    # ---------------------------------------------------------------- monitoring

    def count(self, link, frame):
        """Records the rows that passed a link (the Director's link monitor) and returns the frame."""
        self.rows[link] = self.rows.get(link, 0) + len(frame)
        return frame

    def info(self, message, *args):
        self.log.info(message, *args)

    def warn(self, message, *args):
        self.warnings += 1
        self.log.warning(message, *args)

    def reject(self, stage, row_number, error):
        """A row failed in a stage without a reject link: DataStage logs a warning and drops it."""
        seen = self.rejects.get(stage, 0) + 1
        self.rejects[stage] = seen
        self.warnings += 1
        if seen <= self.MAX_LOGGED_REJECTS:
            self.log.warning("%s: row %s dropped: %s", stage, row_number, error)
        elif seen == self.MAX_LOGGED_REJECTS + 1:
            self.log.warning("%s: further dropped rows are counted but not logged", stage)

    def abort(self, message):
        raise JobAborted("%s: %s" % (self.job_name, message))

    def finish(self):
        """Logs the link counts and returns the job status: RUNOK, or RUNWARN when warnings were logged."""
        for link, rows in self.rows.items():
            self.log.info("link %s: %d row(s)", link, rows)
        for stage, rows in self.rejects.items():
            self.log.warning("stage %s dropped %d row(s)", stage, rows)
        return DSJS.RUNWARN if self.warnings else DSJS.RUNOK
