"""Runtime for Airflow DAGs generated by ds2af from DataStage job sequences.

Every activity task records an ActivityResult in XCom (key "ds_result"); trigger expressions such as
``JA_Load.$JobStatus = DSJS.RUNOK`` read it back through ``SequenceState.act``. This module is imported
when Airflow parses DAG files, so it imports nothing heavy at module level.
"""

from __future__ import annotations

import datetime as _dt
import importlib
import json
import logging
import os
import re
import shlex
import socket
import subprocess
import time
import traceback

from .dsfunc import DSJS, FM, NotTranslated, to_str

log = logging.getLogger("ds2af.sequence")

RESULT_KEY = "ds_result"
_OK_STATUSES = (DSJS.RUNOK, DSJS.RUNWARN)
_PARAM_REFERENCE = re.compile(r"#([A-Za-z_$][A-Za-z0-9_.$]*)#")


def _airflow_exception(name):
    for module in ("airflow.exceptions", "airflow.sdk.exceptions"):
        try:
            return getattr(importlib.import_module(module), name)
        except (ImportError, AttributeError):
            continue
    return None


def _fail(message):
    """Fails the task without retries (outside Airflow: RuntimeError)."""
    exception = _airflow_exception("AirflowFailException") or RuntimeError
    raise exception(message)


def _skip(message):
    """Skips the task, and with it the downstream tasks that wait for its success."""
    exception = _airflow_exception("AirflowSkipException") or RuntimeError
    raise exception(message)


def not_converted(s, activity, reason):
    raise NotTranslated("activity %s of sequence %s was not converted: %s" % (activity, s.sequence, reason))


class ActivityResult:
    """What an activity produced: the $JobStatus, $UserStatus, $ReturnValue, $CommandOutput... of DataStage."""

    def __init__(self, name, kind, job_status=None, user_status="", return_value=None, command_output="",
                 job_name=None, error=None, variables=None, counter=None, found=None):
        self.name = name
        self.kind = kind
        self.job_status = job_status
        self.user_status = user_status
        self.return_value = return_value
        self.command_output = command_output
        self.job_name = job_name
        self.error = error
        self.variables = dict(variables or {})
        self.counter = counter
        self.found = found

    @property
    def ok(self):
        if self.kind == "job":
            return self.job_status == DSJS.RUNOK
        if self.kind == "command":
            return self.return_value == 0
        if self.kind == "file":
            return bool(self.found)
        return self.error is None

    @property
    def warning(self):
        return self.kind == "job" and self.job_status == DSJS.RUNWARN

    @property
    def failed(self):
        if self.kind == "job":
            return self.job_status not in _OK_STATUSES
        if self.kind == "command":
            return self.return_value != 0
        if self.kind == "file":
            return not self.found
        return self.error is not None

    def as_dict(self):
        return {
            "name": self.name, "kind": self.kind, "job_status": self.job_status, "user_status": self.user_status,
            "return_value": self.return_value, "command_output": self.command_output, "job_name": self.job_name,
            "error": self.error, "variables": self.variables, "counter": self.counter, "found": self.found,
        }

    @classmethod
    def from_dict(cls, data):
        data = dict(data or {})
        return cls(data.pop("name", "?"), data.pop("kind", "unknown"), **data)

    def __repr__(self):
        return "ActivityResult(%s, %s, status=%s, rv=%r)" % (self.name, self.kind, self.job_status, self.return_value)


class DsJobConfig:
    """How to reach DataStage for activities that still run there. An Airflow Variable (JSON, name in
    ``variable``) can override any field at run time, e.g. {"ssh_conn_id": "ds_server"}."""

    FIELDS = ("project", "dsjob", "server", "user", "password", "ssh_conn_id", "warn_limit")

    def __init__(self, project, dsjob="dsjob", server=None, user=None, password=None, ssh_conn_id=None,
                 warn_limit=None, variable="ds2af_dsjob"):
        self.project = project
        self.dsjob = dsjob
        self.server = server
        self.user = user
        self.password = password
        self.ssh_conn_id = ssh_conn_id
        self.warn_limit = warn_limit
        self.variable = variable

    def effective(self):
        values = {f: getattr(self, f) for f in self.FIELDS}
        override = None
        try:
            try:
                from airflow.models import Variable
            except ImportError:
                from airflow.sdk import Variable
            override = Variable.get(self.variable, default_var=None) if hasattr(Variable, "setdefault") else Variable.get(self.variable, default=None)
        except Exception:
            override = os.environ.get(self.variable.upper())
        if override:
            values.update(json.loads(override) if isinstance(override, str) else dict(override))
        return DsJobConfig(variable=self.variable, **values)


class SequenceState:
    """The view of one sequence run from inside a task: parameters, activity results, loop counters."""

    def __init__(self, context, sequence, defaults=None, tasks=None, project=""):
        self.context = context or {}
        self.sequence = sequence
        self.project = project
        self.tasks = dict(tasks or {})
        self.ti = self.context.get("ti") or self.context.get("task_instance")
        self.params = {k: ("" if v is None else to_str(v)) for k, v in dict(defaults or {}).items()}
        for key, value in dict(self.context.get("params") or {}).items():
            self.params[key] = "" if value is None else to_str(value)
        self.counters = {}
        self._results = {}

    # ---------------------------------------------------------------- parameters and macros

    def param(self, name):
        if name in self.params:
            return self.params[name]
        if name.startswith("$"):
            return os.environ.get(name[1:], "")
        raise NotTranslated("sequence %s has no parameter %s" % (self.sequence, name))

    def expand(self, text):
        if text is None:
            return None

        def replace(match):
            name = match.group(1)
            if name in self.params:
                return self.params[name]
            if name.startswith("$"):
                return os.environ.get(name[1:], "")
            return match.group(0)

        return _PARAM_REFERENCE.sub(replace, text)

    def _start(self):
        for key in ("logical_date", "execution_date"):
            value = self.context.get(key)
            if value is not None:
                return value
        dag_run = self.context.get("dag_run")
        start = getattr(dag_run, "start_date", None)
        return start or _dt.datetime.now()

    def macro(self, name):
        key = name.upper()
        start = self._start()
        if key == "DSJOBNAME":
            return self.sequence
        if key == "DSPROJECTNAME":
            return self.project
        if key in ("DSJOBINVOCATIONID", "DSJOBCONTROLLER"):
            return ""
        if key == "DSHOSTNAME":
            return socket.gethostname()
        if key == "DSJOBSTARTDATE":
            return start.strftime("%Y-%m-%d")
        if key == "DSJOBSTARTTIME":
            return start.strftime("%H:%M:%S")
        if key == "DSJOBSTARTTIMESTAMP":
            return start.strftime("%Y-%m-%d %H:%M:%S")
        if key == "DSJOBWAVENO":
            return 0
        raise NotTranslated("unknown DataStage macro %s" % name)

    # ---------------------------------------------------------------- activity results

    def record(self, result):
        self._results[result.name] = result
        if self.ti is not None:
            self.ti.xcom_push(key=result_key(result.name), value=result.as_dict())
        return result

    def error(self, name):
        """$ErrSource / $ErrNumber / $ErrMessage of an exception handler: not available in Airflow."""
        log.warning("%s is not available after migration; an empty value is used", name)
        return ""

    def act(self, name):
        if name in self._results:
            return self._results[name]
        data = None
        if self.ti is not None:
            data = self.ti.xcom_pull(task_ids=self.tasks.get(name, name), key=result_key(name))
        if isinstance(data, list):
            data = data[-1] if data else None
        result = ActivityResult.from_dict(data) if data else ActivityResult(name, "unknown", job_status=DSJS.NOTRUNNING)
        self._results[name] = result
        return result

    def user_var(self, activity, variable):
        return self.act(activity).variables.get(variable, "")

    def counter(self, loop):
        if loop in self.counters:
            return self.counters[loop]
        return self.act(loop).counter


def result_key(activity):
    """XCom key of an activity's result (several activities can share one task, e.g. in a loop)."""
    return RESULT_KEY + "." + activity


def state(context, sequence, defaults=None, tasks=None, project=""):
    return SequenceState(context, sequence, defaults, tasks, project)


def routine(module, name):
    """A routine from the generated routines module, for routine calls inside expressions."""
    return getattr(importlib.import_module(module), name)


# --------------------------------------------------------------------------- job activities

def run_job(s, activity, job, params=None, module=None, dsjob=None, invocation_id=None, action="run",
            fail_on_error=True, on_warning="ok", need_user_status=False):
    """Runs a DataStage job: its converted Python module when ``module`` is given, else through dsjob.

    on_warning: "ok" (warnings count as success), "skip" (skip the task and its OK-triggered
    downstream, as DataStage does not fire OK triggers on warnings) or "fail"."""
    params = {k: ("" if v is None else to_str(v)) for k, v in (params or {}).items()}
    if module:
        status, user_status, error = _run_python_job(s, job, module, params, invocation_id)
    else:
        config = (dsjob or DsJobConfig(s.project)).effective()
        status, user_status, error = _run_dsjob(config, job, params, action, invocation_id, need_user_status)
    result = s.record(ActivityResult(activity, "job", job_status=status, user_status=user_status, job_name=job, error=error))
    log.info("activity %s: job %s finished with status %s", activity, job, status)
    if fail_on_error and result.failed:
        _fail("activity %s: job %s failed (status %s)%s" % (activity, job, status, ": " + error if error else ""))
    if result.warning and on_warning == "fail":
        _fail("activity %s: job %s finished with warnings" % (activity, job))
    if result.warning and on_warning == "skip":
        _skip("activity %s: job %s finished with warnings, so its OK triggers do not fire" % (activity, job))
    return result


def _run_python_job(s, job, module, params, invocation_id):
    from .job import JobContext

    target = importlib.import_module(module)
    context = JobContext(job, getattr(target, "PARAMETERS", ()), params, project=s.project,
                         invocation_id=invocation_id, controller=s.sequence)
    try:
        status = target.run(params, context=context)
        return (status if status is not None else DSJS.RUNOK), context.user_status, None
    except Exception as exc:  # the job aborted
        log.error("job %s aborted:\n%s", job, traceback.format_exc())
        return DSJS.RUNFAILED, context.user_status, "%s: %s" % (type(exc).__name__, exc)


def dsjob_command(config, job, params, mode=None, invocation_id=None):
    command = [config.dsjob]
    if config.server:
        command += ["-server", config.server]
    if config.user:
        command += ["-user", config.user]
    if config.password:
        command += ["-password", config.password]
    command += ["-run", "-jobstatus"]
    if mode:
        command += ["-mode", mode]
    if config.warn_limit is not None:
        command += ["-warn", str(config.warn_limit)]
    for key, value in params.items():
        command += ["-param", "%s=%s" % (key, value)]
    command += [config.project, job + ("." + invocation_id if invocation_id else "")]
    return command


def _execute(config, command, shell=False):
    if config.ssh_conn_id:
        from airflow.providers.ssh.hooks.ssh import SSHHook

        text = command if isinstance(command, str) else " ".join(shlex.quote(c) for c in command)
        with SSHHook(ssh_conn_id=config.ssh_conn_id).get_conn() as client:
            _, stdout, stderr = client.exec_command(text)
            output = stdout.read().decode(errors="replace") + stderr.read().decode(errors="replace")
            return stdout.channel.recv_exit_status(), output
    completed = subprocess.run(command, shell=shell, capture_output=True, text=True)
    return completed.returncode, (completed.stdout or "") + (completed.stderr or "")


_FINAL_STATUSES = {1: DSJS.RUNOK, 2: DSJS.RUNWARN, 3: DSJS.RUNFAILED, 11: DSJS.RUNOK, 12: DSJS.RUNWARN,
                   13: DSJS.RUNFAILED, 21: DSJS.RUNOK, 96: DSJS.CRASHED, 97: DSJS.STOPPED,
                   98: DSJS.NOTRUNNABLE, 99: DSJS.NOTRUNNING}


def _job_info(config, job, invocation_id):
    command = [config.dsjob]
    if config.server:
        command += ["-server", config.server]
    if config.user:
        command += ["-user", config.user]
    if config.password:
        command += ["-password", config.password]
    command += ["-jobinfo", config.project, job + ("." + invocation_id if invocation_id else "")]
    _, output = _execute(config, command)
    info = {}
    for line in output.splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            info[key.strip()] = value.strip()
    return info


def _run_dsjob(config, job, params, action, invocation_id, need_user_status):
    if action == "reset_then_run":
        status_text = _job_info(config, job, invocation_id).get("Job Status", "")
        match = re.search(r"\((\d+)\)", status_text)
        if match and int(match.group(1)) in (DSJS.RUNFAILED, DSJS.STOPPED, DSJS.CRASHED):
            _execute(config, dsjob_command(config, job, {}, "RESET", invocation_id))
    mode = {"validate": "VALIDATE", "reset": "RESET"}.get(action)
    code, output = _execute(config, dsjob_command(config, job, params, mode, invocation_id))
    log.info("dsjob %s exited with %s\n%s", job, code, output)
    status = _FINAL_STATUSES.get(code, DSJS.RUNFAILED)
    user_status = ""
    if need_user_status:
        user_status = _job_info(config, job, invocation_id).get("User Status", "")
        if user_status == "not available":
            user_status = ""
    error = None if status in _OK_STATUSES else "dsjob exit code %s" % code
    return status, user_status, error


# --------------------------------------------------------------------------- other activities

def run_routine(s, activity, routine, args, module, fail_on_error=True):
    """Calls the Python port of a server routine from the generated routines module."""
    target = importlib.import_module(module)
    function = getattr(target, routine, None)
    if function is None:
        lowered = routine.lower()
        function = next((getattr(target, n) for n in dir(target) if n.lower() == lowered), None)
    error = None
    value = None
    if function is None:
        error = "routine %s not found in %s" % (routine, module)
    else:
        try:
            value = function(*args)
        except Exception as exc:
            log.error("routine %s failed:\n%s", routine, traceback.format_exc())
            error = "%s: %s" % (type(exc).__name__, exc)
    result = s.record(ActivityResult(activity, "routine", return_value=value, error=error))
    if fail_on_error and result.failed:
        _fail("activity %s: routine %s failed: %s" % (activity, routine, error))
    return result


def run_command(s, activity, command, arguments="", fail_on_error=True, ssh_conn_id=None):
    """Execute Command activity: runs through the shell; $CommandOutput holds the output lines
    separated by field marks, $ReturnValue the exit code."""
    text = (command or "") + ((" " + arguments) if arguments else "")
    code, output = _execute(DsJobConfig("", ssh_conn_id=ssh_conn_id), text, shell=True)
    lines = output.replace("\r\n", "\n").rstrip("\n").split("\n") if output else []
    result = s.record(ActivityResult(activity, "command", return_value=code, command_output=FM.join(lines)))
    log.info("activity %s: %s returned %s", activity, text, code)
    if fail_on_error and result.failed:
        _fail("activity %s: command %r returned %s" % (activity, text, code))
    return result


def send_notification(s, activity, recipients, subject="", body="", sender=None, smtp_server=None,
                      attachments=None, include_status=False):
    """Notification activity: uses Airflow's e-mail setup, falling back to the activity's SMTP server."""
    to = [r.strip() for r in re.split(r"[;,\s]+", recipients or "") if r.strip()]
    text = body or ""
    if include_status:
        text += "\n\nSequence %s activity results:\n%s" % (s.sequence, "\n".join(_status_lines(s)) or "  (none)")
    files = [a for a in re.split(r"[;,]", attachments or "") if a.strip()]
    try:
        try:
            from airflow.utils.email import send_email
            send_email(to=to, subject=subject, html_content=text.replace("\n", "<br>"), files=files or None)
        except ImportError:
            from airflow.providers.smtp.hooks.smtp import SmtpHook
            with SmtpHook() as hook:
                hook.send_email_smtp(to=to, subject=subject, html_content=text.replace("\n", "<br>"),
                                     from_email=sender, files=files or None)
    except ImportError:
        import smtplib
        from email.message import EmailMessage

        message = EmailMessage()
        message["From"] = sender or "datastage@localhost"
        message["To"] = ", ".join(to)
        message["Subject"] = subject
        message.set_content(text)
        with smtplib.SMTP(smtp_server or "localhost") as client:
            client.send_message(message)
    return s.record(ActivityResult(activity, "notification"))


_STATUS_TEXT = {DSJS.RUNOK: "finished OK", DSJS.RUNWARN: "finished with warnings", DSJS.RUNFAILED: "aborted",
                DSJS.CRASHED: "crashed", DSJS.STOPPED: "stopped", DSJS.NOTRUNNABLE: "not compiled"}


def _status_lines(s):
    """One line per activity that has run in this DAG run, read from XCom (the job status report of DataStage)."""
    lines = []
    for name in s.tasks:
        result = s.act(name)
        if result.kind == "unknown":
            continue
        if result.kind == "job":
            detail = "job %s %s" % (result.job_name, _STATUS_TEXT.get(result.job_status, "status %s" % result.job_status))
        elif result.kind in ("command", "routine", "loop"):
            detail = "%s returned %r" % (result.kind, result.return_value)
        else:
            detail = result.kind
        if result.error:
            detail += " (%s)" % result.error
        lines.append("  %s: %s" % (name, detail))
    return lines


def check_file(s, activity, path, appear=True):
    """One poke of a Wait-For-File activity: True once the file exists (or is gone)."""
    exists = os.path.exists(path)
    done = exists if appear else not exists
    if done:
        s.record(ActivityResult(activity, "file", found=True))
    return done


def wait_for_file(s, activity, path, appear=True, timeout=None, poke_interval=60):
    """Polls inside the task; used when the activity's triggers handle the timeout."""
    deadline = None if timeout is None else time.monotonic() + timeout
    while True:
        exists = os.path.exists(path)
        if exists == appear:
            return s.record(ActivityResult(activity, "file", found=True))
        if deadline is not None and time.monotonic() >= deadline:
            return s.record(ActivityResult(activity, "file", found=False))
        time.sleep(poke_interval)


def record_variables(s, activity, values):
    """User Variables activity."""
    return s.record(ActivityResult(activity, "uservars", variables={k: to_str(v) for k, v in values.items()}))


def loop_values(numeric=True, start=1, step=1, end=1, values="", delimiter=","):
    """Values of a Start Loop activity: a numeric range (inclusive) or a delimited list."""
    if numeric:
        first, increment, last = int(to_str(start)), int(to_str(step) or 1), int(to_str(end))
        if increment == 0:
            raise NotTranslated("loop step is 0")
        current = first
        while (increment > 0 and current <= last) or (increment < 0 and current >= last):
            yield current
            current += increment
        return
    separator = {"comma": ",", "space": " ", "tab": "\t"}.get((delimiter or ",").lower(), delimiter or ",")
    for item in to_str(values or "").split(separator):
        if item != "":
            yield item


def set_counter(s, loop, value):
    s.counters[loop] = value
    s._results[loop] = ActivityResult(loop, "loop", counter=value)


def record_loop(s, loop, iterations):
    """Result of a whole loop task: the last counter value and the number of iterations."""
    return s.record(ActivityResult(loop, "loop", counter=s.counters.get(loop), return_value=iterations))


def terminate(s, activity, message=None):
    s.record(ActivityResult(activity, "terminator"))
    _fail(message or "sequence %s stopped by terminator activity %s" % (s.sequence, activity))


def route(s, result, targets, auto_handle_failures=True, always=None):
    """Return value of a branching activity: the task ids of the triggers that fired. An activity that
    failed without any trigger handling it fails the run, as DataStage does when "automatically handle
    activities that fail" is set. ``always`` (the exception handler) stays selected so that Airflow does
    not skip it; its own trigger rule decides whether it runs."""
    if not targets and result is not None and result.failed and auto_handle_failures:
        _fail("activity %s failed and none of its triggers handles the failure" % result.name)
    return list(dict.fromkeys(list(targets) + list(always or [])))
