using System.Linq;
using System.Text;
using DataStage2Airflow.Model;
using DataStage2Airflow.Reporting;

namespace DataStage2Airflow.Generation
{
    /// <summary>A one-task DAG for a job that no sequence runs (DataStage jobs can be scheduled on their own).</summary>
    public static class JobDagGenerator
    {
        /// <param name="module">Converted Python module, or null to run the job in DataStage through dsjob.</param>
        public static string Generate(DsJob job, DsProject project, MigrationOptions options, string dagId, string? module)
        {
            var w = new PythonWriter();
            var doc = new StringBuilder();
            doc.Append(job.Name).Append("\n\n");
            doc.Append($"Generated by {new MigrationReport(string.Empty).Tool} for DataStage {job.Kind.ToString().ToLowerInvariant()} job {job.Name} (project {project.Name}),\n");
            doc.Append("which no job sequence runs. ");
            doc.Append(module != null ? $"It runs the converted Python job {module}.\n" : "It runs the job in DataStage through dsjob.\n");
            if (job.Description.Trim().Length > 0) doc.Append('\n').Append(job.Description.Trim()).Append('\n');
            w.Docstring(doc.ToString());
            w.Line();
            w.Line("from __future__ import annotations");
            w.Line();
            w.Line("import datetime");
            w.Line();
            w.Lines(SequenceGenerator.AirflowImports(options.Airflow, false, false));
            w.Line();
            w.Line("from ds2af_runtime import sequence as seq");
            w.Line();
            var taskId = Naming.AirflowId(job.Name);
            w.Line($"JOB = {Py.Str(job.Name)}");
            w.Line($"PROJECT = {Py.Str(project.Name)}");
            w.Line("PARAMETERS = {");
            w.Indent();
            foreach (var p in job.Parameters.Where(p => !p.IsEnvironmentVariable))
            {
                w.Line($"{Py.Str(p.Name)}: {Py.Str(p.Type == ParameterType.Encrypted ? string.Empty : p.DefaultValue)},");
            }

            w.Dedent();
            w.Line("}");
            if (module == null)
            {
                var args = new System.Collections.Generic.List<string> { "PROJECT", $"dsjob={Py.Str(options.DsjobPath)}" };
                if (options.DsjobServer != null) args.Add($"server={Py.Str(options.DsjobServer)}");
                if (options.DsjobSshConnId != null) args.Add($"ssh_conn_id={Py.Str(options.DsjobSshConnId)}");
                w.Line($"DSJOB = seq.DsJobConfig({string.Join(", ", args)})");
            }

            w.Line();
            w.Line();
            SequenceGenerator.DagHeader(w, options, project, job, dagId, "job", job.Parameters);
            w.Indent();
            w.Line();
            w.Line($"@task(task_id={Py.Str(taskId)})");
            using (w.Block("def run_job(**context):"))
            {
                w.Docstring($"Runs {job.Name} with the DAG run's parameters.");
                w.Line($"s = seq.state(context, JOB, PARAMETERS, {{JOB: {Py.Str(taskId)}}}, PROJECT)");
                w.Line("params = {name: s.param(name) for name in PARAMETERS}");
                var implementation = module != null ? $"module={Py.Str(module)}" : "dsjob=DSJOB";
                var warning = options.FailOnWarning ? ", on_warning=\"fail\"" : string.Empty;
                w.Line($"return seq.run_job(s, JOB, JOB, params=params, {implementation}{warning}).as_dict()");
            }

            w.Line();
            w.Line("run_job()");
            w.Dedent();
            return w.ToString();
        }
    }
}
